// 200-day curriculum: 50 real-life categories x 20 items each = 1000 micro-scenarios.
// Each item expands into one scenario: an NPC line, a target response built from
// the item, and keywords used to check the learner's spoken/typed answer.
// Categories are ordered roughly easy -> harder, so Day 1 starts with simple topics.

const CATEGORY_TEMPLATES = [
  {
    id: "greetings_intro",
    title: "인사와 자기소개",
    npc: "Hi there! I don't think we've met. What's your name?",
    template: (item) => `My name is ${item}. Nice to meet you.`,
    items: ["Alex", "Jordan", "Sam", "Taylor", "Jamie", "Chris", "Morgan", "Casey", "Riley", "Drew",
      "Min-jun", "Ji-woo", "Seo-yeon", "Do-yoon", "Ha-eun", "Yu-jin", "Joon-ho", "Eun-ji", "Tae-yang", "Su-bin"],
  },
  {
    id: "smalltalk_weather",
    title: "날씨 스몰토크",
    npc: "Quite a day out there, isn't it? What do you think of the weather?",
    template: (item) => `It's ${item} today, isn't it?`,
    items: ["sunny", "cloudy", "rainy", "windy", "freezing", "humid", "chilly", "warm", "snowing", "foggy",
      "boiling hot", "pretty mild", "getting colder", "clearing up", "about to rain", "really nice",
      "a bit gloomy", "perfect for a walk", "unusually dry", "storming"],
  },
  {
    id: "smalltalk_weekend",
    title: "주말 이야기",
    npc: "So, any plans for the weekend?",
    template: (item) => `I'm planning to ${item} this weekend.`,
    items: ["go hiking", "watch a movie", "visit my family", "clean my apartment", "go grocery shopping",
      "meet some friends", "relax at home", "go to the gym", "read a book", "try a new restaurant",
      "go to the beach", "work on a project", "take a day trip", "go camping", "play video games",
      "go cycling", "cook a big meal", "catch up on sleep", "go to a concert", "do some gardening"],
  },
  {
    id: "smalltalk_hobby",
    title: "취미 이야기",
    npc: "What do you like to do in your free time?",
    template: (item) => `In my free time, I like to ${item}.`,
    items: ["play guitar", "paint", "go running", "play basketball", "bake", "knit", "play chess",
      "take photos", "write in a journal", "go fishing", "watch documentaries", "play the piano",
      "do yoga", "collect stamps", "garden", "play board games", "swim", "go rock climbing",
      "learn languages", "build models"],
  },
  {
    id: "smalltalk_family",
    title: "가족 이야기",
    npc: "Do you have any brothers or sisters?",
    template: (item) => `Yes, I have ${item}.`,
    items: ["an older brother", "a younger sister", "two older sisters", "one younger brother",
      "twin siblings", "three siblings", "no siblings, I'm an only child", "a brother and a sister",
      "a big family with four kids", "just one younger sister", "an older brother and a younger brother",
      "two brothers", "a half-sister", "a stepbrother", "a large extended family nearby",
      "one sibling who lives abroad", "a sister who's a doctor", "a brother in college",
      "cousins who live close by", "grandparents living with us"],
  },
  {
    id: "making_plans",
    title: "약속 잡기",
    npc: "Are you free sometime this week? Want to grab a bite?",
    template: (item) => `Sure, how about ${item}?`,
    items: ["Monday evening", "Tuesday at noon", "Wednesday after work", "Thursday morning",
      "Friday night", "Saturday afternoon", "Sunday brunch", "tomorrow at 7", "next Monday",
      "later this week", "this weekend", "early next week", "Thursday at lunchtime",
      "Friday around 6", "Saturday evening", "sometime Wednesday", "Tuesday evening",
      "the day after tomorrow", "this coming Sunday", "whenever works for you"],
  },
  {
    id: "coffee_order",
    title: "카페에서 음료 주문하기",
    npc: "Hi! What can I get started for you today?",
    template: (item) => `I'll have ${item}, please.`,
    items: ["a latte", "a cappuccino", "an iced americano", "a hot chocolate", "an espresso",
      "a cold brew", "a mocha", "a green tea", "a chai latte", "a caramel macchiato",
      "a flat white", "an iced tea", "a hazelnut latte", "a decaf coffee", "a matcha latte",
      "an affogato", "a vanilla latte", "a black coffee", "a frappuccino", "a lemonade"],
  },
  {
    id: "fastfood_order",
    title: "패스트푸드 주문하기",
    npc: "Welcome! What would you like to order today?",
    template: (item) => `Can I get ${item}, please?`,
    items: ["a cheeseburger", "a chicken sandwich", "a large fries", "a fish burger", "a veggie burger",
      "a small soda", "chicken nuggets", "onion rings", "a hot dog", "a taco combo",
      "a burrito bowl", "a slice of pizza", "a milkshake", "a salad", "a wrap",
      "a bacon burger", "a double cheeseburger meal", "an ice cream cone", "a fried chicken combo",
      "a value meal"],
  },
  {
    id: "restaurant_order",
    title: "레스토랑에서 메뉴 주문",
    npc: "Are you ready to order? What would you like today?",
    template: (item) => `I'll have the ${item}, please.`,
    items: ["grilled salmon", "steak", "pasta carbonara", "Caesar salad", "mushroom risotto",
      "roast chicken", "fish and chips", "vegetable curry", "lamb chops", "seafood pasta",
      "beef stew", "tomato soup", "duck breast", "pork ribs", "grilled shrimp",
      "spaghetti bolognese", "margherita pizza", "shrimp tacos", "chicken parmesan", "vegetable stir-fry"],
  },
  {
    id: "directions_ask",
    title: "길 물어보기",
    npc: "Excuse me, could I ask you something?",
    template: (item) => `Could you tell me how to get to ${item}?`,
    items: ["the nearest subway station", "the bus stop", "the train station", "the post office",
      "the closest pharmacy", "city hall", "the museum", "the shopping mall", "the airport",
      "the nearest bank", "the library", "the hospital", "the police station", "the park",
      "the nearest gas station", "the beach", "the stadium", "the university", "the market",
      "downtown"],
  },
  {
    id: "give_directions",
    title: "길 알려주기",
    npc: "Excuse me, do you know where the nearest station is?",
    template: (item) => `Sure, go straight and ${item}.`,
    items: ["turn left at the corner", "turn right at the light", "it's on your right",
      "it's just across the street", "go past the bank", "take the second left",
      "it's two blocks down", "follow this road for five minutes", "it's next to the bakery",
      "cross the street and it's there", "go up the hill", "it's behind the church",
      "take the elevator to the second floor", "it's right next to the entrance",
      "go through the park", "it's at the end of this street", "keep walking straight",
      "take the first right", "it's opposite the cafe", "it's a five-minute walk from here"],
  },
  {
    id: "taxi_destination",
    title: "택시 타기",
    npc: "Where to?",
    template: (item) => `${item}, please.`,
    items: ["The airport", "Downtown, near the city hall", "This address, please",
      "The Grand Hotel", "The central train station", "The nearest hospital",
      "123 Main Street", "The convention center", "The shopping district",
      "The university campus", "The ferry terminal", "Riverside Park",
      "The stadium", "The old town", "The business district",
      "The bus terminal", "That building over there", "The nearest subway entrance",
      "The harbor", "Just around the corner"],
  },
  {
    id: "bus_ask",
    title: "버스 이용하기",
    npc: "Can I help you find a bus?",
    template: (item) => `Does this bus go to ${item}?`,
    items: ["downtown", "the airport", "the train station", "city hall", "the university",
      "the shopping mall", "the beach", "the stadium", "the hospital", "the museum",
      "the market", "the harbor", "the old town", "the business district", "the park",
      "the library", "the convention center", "the zoo", "the botanical garden", "the ferry terminal"],
  },
  {
    id: "subway_ask",
    title: "지하철 이용하기",
    npc: "Excuse me, do you know which line I need?",
    template: (item) => `You'll need to take ${item}.`,
    items: ["the red line", "the blue line", "line 2", "the green line", "line 5",
      "the express train", "the yellow line", "line 3, then transfer at Central",
      "the orange line", "the airport line", "line 1 toward downtown", "the purple line",
      "the circle line", "line 4, two stops from here", "the local train, not the express",
      "the blue line, then walk five minutes", "line 7", "the north-bound line",
      "the last train of the night", "any train heading downtown"],
  },
  {
    id: "hotel_checkin",
    title: "호텔 체크인",
    npc: "Welcome! Do you have a reservation with us?",
    template: (item) => `Yes, I booked ${item}.`,
    items: ["a single room", "a double room", "a room with a city view", "a room with two beds",
      "a suite for two nights", "a non-smoking room", "a room on a high floor", "a deluxe room",
      "a room with breakfast included", "an ocean view room", "a family room",
      "a room for three nights", "a king-size room", "an early check-in",
      "a room near the elevator", "a quiet room", "a room with a balcony",
      "a twin room", "a room under my company's name", "a late check-out"],
  },
  {
    id: "hotel_roomservice",
    title: "호텔 룸서비스",
    npc: "Room service, how can I help you?",
    template: (item) => `Could you send up ${item}?`,
    items: ["some extra towels", "a bottle of water", "breakfast for two", "an extra pillow",
      "a wake-up call at 7", "a hair dryer", "some coffee", "an iron and ironing board",
      "extra toiletries", "a blanket", "some ice", "a menu", "a toothbrush",
      "slippers", "a laundry bag", "the newspaper", "a charger cable",
      "an extra key card", "a late checkout confirmation", "directions to the gym"],
  },
  {
    id: "hotel_checkout",
    title: "호텔 체크아웃",
    npc: "Good morning! Checking out today?",
    template: (item) => `Yes, and could you also ${item}?`,
    items: ["print my receipt", "check my minibar charges", "call a taxi for me",
      "hold my luggage until 3pm", "arrange a late checkout", "confirm the total on my card",
      "check if I have any pending charges", "help me with my bags",
      "give me a copy of the invoice", "double check my checkout time",
      "recommend a place for breakfast nearby", "store my bags for a few hours",
      "tell me how to get to the airport", "confirm my refund for the extra night",
      "check me out from room 402", "provide a taxi voucher",
      "verify there's no outstanding balance", "print a copy for my company",
      "check if the shuttle is still running", "let the manager know I enjoyed my stay"],
  },
  {
    id: "airport_checkin",
    title: "공항 체크인",
    npc: "Good morning! May I see your passport and ticket, please?",
    template: (item) => `Sure, and I'd like ${item}.`,
    items: ["a window seat", "an aisle seat", "to check one bag", "to check two bags",
      "an extra legroom seat", "a seat near the front", "a seat next to my friend",
      "to upgrade to business class", "a vegetarian meal", "to confirm my connecting flight",
      "an earlier flight if possible", "a seat away from the emergency exit",
      "to add my frequent flyer number", "a boarding pass printed, please",
      "a seat with more legroom", "to check my carry-on due to its size",
      "a seat toward the back", "priority boarding", "to confirm my baggage allowance",
      "to know my gate number"],
  },
  {
    id: "airport_security",
    title: "공항 보안검색",
    npc: "Please place your belongings in the tray. Do you have any electronics or liquids?",
    template: (item) => `Yes, I have ${item}.`,
    items: ["a laptop", "a tablet", "a small bottle of water", "some liquid medicine",
      "a phone charger", "a camera", "duty-free perfume", "a power bank",
      "a bottle of sunscreen under 100ml", "a pair of headphones", "a portable fan",
      "some snacks", "a laptop and a tablet", "contact lens solution",
      "an electric razor", "a small umbrella", "a book and a laptop",
      "nothing to declare", "a spare battery", "prescription medicine"],
  },
  {
    id: "airport_immigration",
    title: "공항 입국심사",
    npc: "What's the purpose of your visit?",
    template: (item) => `I'm here for ${item}.`,
    items: ["vacation", "business", "a conference", "visiting family", "a study exchange",
      "sightseeing", "a short work trip", "a wedding", "a friend's graduation",
      "a language course", "a job interview", "a music festival", "medical treatment",
      "an internship", "a layover", "volunteer work", "a research project",
      "a honeymoon", "a school trip", "attending a workshop"],
  },
  {
    id: "carrental_pickup",
    title: "렌터카 빌리기",
    npc: "Hi! What kind of car are you looking for today?",
    template: (item) => `I'd like to rent ${item}.`,
    items: ["a compact car", "an SUV", "a sedan", "a car with automatic transmission",
      "a car with GPS", "a minivan", "a hybrid car", "the cheapest option available",
      "a car for one week", "a car with a child seat", "an electric car",
      "a convertible", "a car with unlimited mileage", "a four-wheel drive",
      "a car with extra insurance", "a car for a one-way trip", "a luxury car",
      "a car that seats seven", "a fuel-efficient car", "a car with a roof rack"],
  },
  {
    id: "carrental_return",
    title: "렌터카 반납하기",
    npc: "Are you returning the car today? Let me check a few things.",
    template: (item) => `Yes, and I made sure to ${item}.`,
    items: ["fill up the gas tank", "clean out my belongings", "check the tire pressure",
      "keep all the original documents", "return it on time", "note the mileage",
      "check for any damage beforehand", "bring both sets of keys",
      "empty the trunk", "return it to the same location", "remove my GPS device",
      "double check the insurance papers", "take photos of the car",
      "return the parking pass", "check the oil level", "wipe down the interior",
      "confirm the final charge", "bring the rental agreement", "return the charging cable",
      "check I didn't leave anything in the glove compartment"],
  },
  {
    id: "grocery_shopping",
    title: "장보기",
    npc: "Hi, can I help you find anything today?",
    template: (item) => `Yes, where can I find ${item}?`,
    items: ["fresh vegetables", "milk", "eggs", "bread", "chicken breast",
      "olive oil", "rice", "pasta", "canned tomatoes", "cereal",
      "frozen vegetables", "yogurt", "cheese", "coffee beans", "spices",
      "bottled water", "snacks", "laundry detergent", "paper towels", "toothpaste"],
  },
  {
    id: "clothes_shopping",
    title: "옷 쇼핑하기",
    npc: "Let me know if you need any help finding your size.",
    template: (item) => `Actually, could I try on ${item}?`,
    items: ["this in a medium", "a smaller size", "a larger size", "this jacket in blue",
      "these jeans in a 32", "this shirt in white", "a different color",
      "this dress in size 8", "these shoes in a 9", "a size up",
      "this sweater in gray", "the same style in black", "this coat in medium",
      "a size small", "this in extra large", "the one in the window",
      "this skirt in size 6", "a size down", "these pants hemmed shorter",
      "this hat, just to see how it looks"],
  },
  {
    id: "shoe_shopping",
    title: "신발 쇼핑하기",
    npc: "What size shoe do you usually wear?",
    template: (item) => `I usually wear ${item}.`,
    items: ["a size 8", "a size 9", "a size 10", "a size 7", "a size 6.5",
      "a size 42 in European sizing", "a size 38", "a wide fit",
      "a narrow fit", "a size 9.5", "a size 11", "a size 40",
      "whatever fits best, I'm flexible", "a size smaller than usual for this brand",
      "a size larger for running shoes", "size 7 in flats", "size 9 in boots",
      "a half size up", "a size 8 in sandals", "a kids' size 4 for my son"],
  },
  {
    id: "returning_item",
    title: "환불/교환하기",
    npc: "Hi, how can I help you today?",
    template: (item) => `I'd like to return this because ${item}.`,
    items: ["it doesn't fit", "it's the wrong size", "it's damaged", "I changed my mind",
      "it doesn't match the description", "I received the wrong item",
      "it stopped working after one use", "I found a cheaper price elsewhere",
      "it was a duplicate gift", "the color is different from the photo",
      "it's missing a part", "I no longer need it", "it arrived late",
      "the packaging was damaged", "it's not what I ordered",
      "it doesn't work with my other devices", "I'd like a refund instead of store credit",
      "it has a defect", "the size chart was misleading", "I simply don't like it"],
  },
  {
    id: "asking_discount",
    title: "할인 물어보기",
    npc: "Is there anything else I can help you with?",
    template: (item) => `Actually, do you have ${item}?`,
    items: ["any discounts today", "a student discount", "a coupon I could use",
      "any ongoing sales", "a loyalty program", "a discount for buying two",
      "a price match policy", "a senior discount", "any promotions this week",
      "a first-time customer discount", "free shipping options",
      "a bundle deal", "any clearance items", "a way to earn points",
      "a discount if I sign up for the newsletter", "a military discount",
      "a group discount", "seasonal sales", "a referral discount code",
      "a better price if I pay in cash"],
  },
  {
    id: "checkout_payment",
    title: "계산하기",
    npc: "That'll be everything. How would you like to pay?",
    template: (item) => `I'll pay by ${item}.`,
    items: ["credit card", "debit card", "cash", "mobile pay", "contactless card",
      "card, split into two payments", "gift card", "credit card, tap to pay",
      "cash, and I'll take the change", "card, and I'd like a receipt",
      "mobile wallet", "card ending in 1234", "cash, exact amount",
      "credit, and could I get it in installments", "my company card",
      "a combination of cash and card", "card, no receipt needed",
      "cash, keep the change", "card, and please double the receipt",
      "whichever is easiest for you"],
  },
  {
    id: "bank_account",
    title: "은행 계좌 개설",
    npc: "Hi, what can I help you with today?",
    template: (item) => `I'd like to ${item}.`,
    items: ["open a checking account", "open a savings account", "apply for a debit card",
      "set up online banking", "close my old account", "update my address",
      "apply for a credit card", "increase my card limit", "get a new PIN",
      "set up automatic transfers", "check my account balance",
      "report a lost card", "transfer money to another account",
      "open a joint account", "get a bank statement", "set up direct deposit",
      "apply for a small loan", "convert my account to a foreign currency account",
      "get information about interest rates", "dispute a charge on my card"],
  },
  {
    id: "currency_exchange",
    title: "환전하기",
    npc: "Welcome, what currency would you like to exchange today?",
    template: (item) => `I'd like to exchange this for ${item}.`,
    items: ["US dollars", "euros", "Japanese yen", "British pounds", "Korean won",
      "Canadian dollars", "Australian dollars", "Chinese yuan", "Thai baht",
      "Vietnamese dong", "Singapore dollars", "Swiss francs", "Mexican pesos",
      "Indian rupees", "Hong Kong dollars", "New Zealand dollars",
      "Philippine pesos", "Malaysian ringgit", "Indonesian rupiah", "Taiwanese dollars"],
  },
  {
    id: "withdraw_cash",
    title: "ATM/현금 인출",
    npc: "Is there anything I can help you with at the counter today?",
    template: (item) => `I'd like to withdraw ${item}, please.`,
    items: ["one hundred dollars", "fifty dollars", "two hundred dollars",
      "some cash for the week", "twenty dollars in small bills",
      "three hundred dollars", "a small amount, just in case",
      "cash for a taxi", "some local currency", "a round number, like a hundred",
      "enough for groceries", "cash for an emergency", "150 dollars",
      "the maximum daily amount", "a few small bills and some coins",
      "cash without a fee if possible", "500 in local currency",
      "a mix of bills and coins", "just enough to cover today's expenses",
      "seventy-five dollars"],
  },
  {
    id: "post_office",
    title: "우체국 이용하기",
    npc: "Hi, what can I help you send today?",
    template: (item) => `I'd like to send ${item}.`,
    items: ["this package overseas", "a letter by express mail", "this box to Korea",
      "a postcard", "this parcel with tracking", "a document by registered mail",
      "this gift to my family", "a fragile item, so please handle with care",
      "this package by the cheapest method", "an envelope internationally",
      "this box, and I need it insured", "a package that needs to arrive by Friday",
      "this letter domestically", "a heavy parcel, so I need to weigh it first",
      "this box with extra padding", "a same-day delivery item",
      "this to a business address", "a return package",
      "this with signature required on delivery", "a bulk shipment"],
  },
  {
    id: "pharmacy",
    title: "약국 이용하기",
    npc: "Hi, how can I help you today?",
    template: (item) => `I have ${item}. What would you recommend?`,
    items: ["a headache", "a sore throat", "a cough", "a stuffy nose", "a fever",
      "an upset stomach", "allergies", "a skin rash", "a toothache",
      "muscle pain", "insomnia", "a bad cold", "motion sickness",
      "a mild burn", "a cut that needs a bandage", "back pain",
      "eye irritation", "seasonal allergies", "a mosquito bite", "heartburn"],
  },
  {
    id: "doctor_visit",
    title: "병원 진료받기",
    npc: "What brings you in today? Tell me how you're feeling.",
    template: (item) => `I've had ${item} for a couple of days.`,
    items: ["a high fever", "a persistent cough", "a sore throat", "stomach pain",
      "a headache", "dizziness", "shortness of breath", "joint pain",
      "a skin rash", "back pain", "nausea", "chest pain",
      "trouble sleeping", "a swollen ankle", "ear pain", "blurry vision",
      "a stiff neck", "loss of appetite", "fatigue", "a persistent runny nose"],
  },
  {
    id: "dentist_appointment",
    title: "치과 진료받기",
    npc: "What seems to be the problem with your teeth today?",
    template: (item) => `I've been having ${item}.`,
    items: ["a toothache", "sensitivity to cold", "a chipped tooth", "bleeding gums",
      "pain when chewing", "a loose filling", "bad breath",
      "swelling around a tooth", "a cracked tooth", "jaw pain",
      "sensitivity to sweets", "gum pain", "a broken crown",
      "pain in my wisdom tooth", "sensitivity to hot drinks",
      "a cavity I think", "trouble flossing because of pain",
      "an ache that comes and goes", "pain after a filling", "trouble with my bite"],
  },
  {
    id: "gym_membership",
    title: "헬스장 등록하기",
    npc: "Hi! Are you interested in becoming a member here?",
    template: (item) => `Yes, I'm interested in ${item}.`,
    items: ["a monthly membership", "a one-year membership", "a trial pass",
      "personal training sessions", "group fitness classes", "a family membership",
      "a membership with pool access", "a student discount plan",
      "a membership I can pause anytime", "a membership with locker access",
      "just the basic plan", "a membership with sauna access",
      "signing up for a free trial first", "a weekend-only membership",
      "a membership that includes yoga classes", "a couples membership",
      "the premium plan with all facilities", "a short-term membership for a month",
      "off-peak hours membership", "a membership with nutrition coaching"],
  },
  {
    id: "gym_class_schedule",
    title: "헬스장 수업 일정 확인",
    npc: "Are you looking for a specific class today?",
    template: (item) => `Yes, what time is ${item}?`,
    items: ["the yoga class", "the spin class", "the boxing class", "the pilates class",
      "the morning HIIT class", "the swimming lesson", "the zumba class",
      "the strength training class", "the evening yoga session",
      "the beginner's class", "the CrossFit class", "the dance cardio class",
      "the stretching class", "the weekend bootcamp", "the kickboxing class",
      "the barre class", "the meditation session", "the aqua aerobics class",
      "the martial arts class", "the core workout class"],
  },
  {
    id: "library_borrow",
    title: "도서관 이용하기",
    npc: "Hi, can I help you find something today?",
    template: (item) => `I'm looking for ${item}.`,
    items: ["a mystery novel", "a science fiction book", "a history book",
      "a children's book for my daughter", "a cookbook", "a biography",
      "a book on learning English", "a graphic novel", "a poetry collection",
      "a travel guide", "a self-help book", "a book club recommendation",
      "an audiobook", "a magazine", "a newspaper archive",
      "a textbook for my class", "a bestseller", "a book in large print",
      "a research journal", "a book to borrow for two weeks"],
  },
  {
    id: "hairdresser",
    title: "미용실 이용하기",
    npc: "Hi! What would you like to do with your hair today?",
    template: (item) => `I'd like ${item}, please.`,
    items: ["a haircut", "a trim, just the ends", "a shorter style",
      "layers added", "my hair dyed brown", "highlights",
      "a blow dry", "a perm", "bangs", "a fade on the sides",
      "a completely new style", "just a wash and style", "my hair straightened",
      "curls for a special event", "a color touch-up",
      "a treatment for damaged hair", "a buzz cut", "a shoulder-length cut",
      "an undercut", "my hair styled for a wedding"],
  },
  {
    id: "phone_reservation",
    title: "전화로 예약하기",
    npc: "Thank you for calling. How can I help you?",
    template: (item) => `I'd like to make a reservation for ${item}.`,
    items: ["two people at 7pm", "four people tomorrow evening", "a table by the window",
      "this Saturday at noon", "six people for a birthday dinner",
      "next Friday at 8pm", "a quiet table for two", "a party of five",
      "this weekend, any time works", "a table outside if possible",
      "3 people at 6:30", "a large group of ten", "next Tuesday at lunch",
      "a table near the entrance", "this evening at 9", "a private room for a meeting",
      "two people, and one has a food allergy", "a table for a business dinner",
      "tomorrow at 1pm", "a family of four"],
  },
  {
    id: "tech_support",
    title: "기술 지원 요청하기",
    npc: "Tech support, how can I help you today?",
    template: (item) => `${item} isn't working properly.`,
    items: ["My laptop", "My internet connection", "My phone screen", "My printer",
      "My email account", "My wifi router", "My smart TV", "My webcam",
      "My keyboard", "My mouse", "The app", "My password reset link",
      "My account login", "My headphones", "My tablet",
      "My charger", "The website", "My speaker",
      "My laptop battery", "My software update"],
  },
  {
    id: "product_complaint",
    title: "제품 불만 제기하기",
    npc: "I'm sorry to hear that. Can you tell me what happened?",
    template: (item) => `${item}.`,
    items: ["The product arrived broken", "It stopped working after two days",
      "It's completely different from the pictures online", "I was charged twice for the same order",
      "The delivery was three weeks late", "I never received my order",
      "The box was empty when it arrived", "The item was missing several parts",
      "Customer service hasn't responded to my emails", "The size doesn't match what I ordered",
      "The product smells strongly of chemicals", "It broke the first time I used it",
      "The color faded after one wash", "I received someone else's order",
      "The warranty wasn't honored", "The instructions were missing",
      "It made a strange noise right out of the box", "The packaging didn't protect it at all",
      "I was overcharged for shipping", "The refund never went through"],
  },
  {
    id: "job_interview",
    title: "면접 답변 연습",
    npc: "So, tell me a little about yourself. What are your strengths?",
    template: (item) => `I'd say one of my strengths is that I'm ${item}.`,
    items: ["very organized", "a good communicator", "quick to learn new things",
      "detail-oriented", "good at solving problems", "a team player",
      "very reliable", "good under pressure", "creative",
      "adaptable to change", "a strong leader", "very patient",
      "good at managing my time", "a fast learner", "good at multitasking",
      "very motivated", "good at giving feedback", "confident in public speaking",
      "very analytical", "passionate about my work"],
  },
  {
    id: "apartment_viewing",
    title: "집 보러 가기",
    npc: "Thanks for coming! What are you looking for in an apartment?",
    template: (item) => `I'm mainly looking for a place with ${item}.`,
    items: ["good natural light", "a nearby subway station", "a quiet neighborhood",
      "a parking space", "a pet-friendly policy", "a gym in the building",
      "two bedrooms", "a balcony", "a modern kitchen",
      "a short commute to downtown", "a low deposit", "a washer and dryer included",
      "high-speed internet already set up", "a secure entrance",
      "a nearby grocery store", "a bathtub, not just a shower",
      "central heating", "storage space", "a rooftop terrace",
      "flexible lease terms"],
  },
  {
    id: "house_rules",
    title: "집/숙소 규칙 물어보기",
    npc: "Before you move in, let me go over a few things.",
    template: (item) => `Just to confirm, is ${item} allowed?`,
    items: ["having a pet", "smoking on the balcony", "having guests overnight",
      "playing music after 10pm", "subletting the room", "painting the walls",
      "hanging pictures on the walls", "using the shared laundry after midnight",
      "parking a second car", "having a small party occasionally",
      "keeping bikes in the hallway", "using the balcony for a small grill",
      "having packages delivered to the front desk", "changing the locks",
      "having a roommate move in later", "storing extra furniture in the garage",
      "using the rooftop after sunset", "having visitors during weekdays",
      "installing a washing machine", "putting up curtains of my own"],
  },
  {
    id: "wifi_password",
    title: "와이파이 비밀번호 묻기",
    npc: "Let me know if you need anything to get settled in.",
    template: (item) => `Actually, could you tell me ${item}?`,
    items: ["the wifi password", "the wifi network name", "if there's a guest network",
      "how to reset the router", "where the router is located",
      "if the wifi covers the whole apartment", "the internet provider's number",
      "if there's a data limit", "how fast the internet speed is",
      "if I need a separate password for the smart TV", "the backup wifi option",
      "how to connect my laptop", "if there's 5G wifi available",
      "the router's admin password", "if guests can use a separate network",
      "how to troubleshoot a weak signal", "if the wifi works on the balcony",
      "the technical support number", "if there's ethernet available too",
      "when the wifi bill is due"],
  },
  {
    id: "movie_recommend",
    title: "영화 추천 대화",
    npc: "Have you seen any good movies lately?",
    template: (item) => `I really enjoyed a ${item} recently.`,
    items: ["romantic comedy", "action movie", "documentary", "horror film",
      "animated movie", "mystery thriller", "science fiction film",
      "historical drama", "musical", "superhero movie",
      "war film", "coming-of-age story", "crime drama",
      "fantasy movie", "psychological thriller", "family movie",
      "indie film", "biographical film", "adventure movie", "comedy special"],
  },
  {
    id: "restaurant_recommend",
    title: "맛집 추천 대화",
    npc: "Do you know any good places to eat around here?",
    template: (item) => `Yeah, there's a great ${item} restaurant nearby.`,
    items: ["Italian", "Japanese", "Korean", "Mexican", "Thai",
      "French", "Indian", "Vietnamese", "Chinese", "Mediterranean",
      "seafood", "vegetarian", "steak", "barbecue", "sushi",
      "ramen", "tapas", "brunch", "fusion", "dessert"],
  },
  {
    id: "borrow_neighbor",
    title: "이웃에게 물건 빌리기",
    npc: "Oh hi! Did you need something?",
    template: (item) => `Sorry to bother you, but could I borrow ${item}?`,
    items: ["a ladder", "some sugar", "a phone charger", "an umbrella",
      "a screwdriver", "some eggs", "a first aid kit", "jumper cables",
      "a vacuum cleaner", "a step stool", "some flour", "a bike pump",
      "an extension cord", "a spare key", "a measuring cup",
      "a flashlight", "a toolbox", "some tape", "a fan for the summer",
      "a few chairs for a small gathering"],
  },
  {
    id: "food_delivery",
    title: "배달 음식 주문하기",
    npc: "Thanks for calling! What would you like to order?",
    template: (item) => `I'd like to order ${item}, please.`,
    items: ["a large pepperoni pizza", "two bowls of ramen", "a chicken curry with rice",
      "a family-size fried chicken combo", "sushi for two", "a vegetable stir-fry",
      "a bacon cheeseburger meal", "pad thai", "a burrito with extra guacamole",
      "three tacos and a soda", "a bibimbap bowl", "a seafood pasta",
      "a large salad with grilled chicken", "dumplings and fried rice",
      "a Hawaiian pizza with extra cheese", "a chicken sandwich meal",
      "pho with extra noodles", "a spicy tofu stew", "a club sandwich",
      "General Tso's chicken with rice"],
  },
];

function buildCurriculum() {
  // Interleave categories round-robin (round 0: item[0] of every category, round
  // 1: item[1] of every category, ...) instead of laying out one category's 20
  // items back to back. Otherwise a single category (20 items = 4 days) would
  // occupy 4 consecutive days with the same NPC line repeated 20 times in a row.
  const itemsPerCategory = CATEGORY_TEMPLATES[0].items.length;
  const scenarios = [];
  for (let round = 0; round < itemsPerCategory; round++) {
    CATEGORY_TEMPLATES.forEach((cat) => {
      const item = cat.items[round];
      scenarios.push({
        categoryId: cat.id,
        categoryTitle: cat.title,
        npc: cat.npc,
        answer: cat.template(item),
        keyword: item.replace(/^(a |an |the )/i, "").split(",")[0].trim(),
      });
    });
  }
  scenarios.forEach((s, i) => {
    s.day = Math.floor(i / 5) + 1;
    s.slot = (i % 5) + 1;
    s.id = `d${s.day}-${s.slot}`;
  });
  return scenarios;
}

const CURRICULUM = buildCurriculum();
const CURRICULUM_TOTAL_DAYS = Math.ceil(CURRICULUM.length / 5);
