// 200-day curriculum: 50 real-life categories x 20 items each = 1000 micro-scenarios.
// Each item expands into one scenario: an NPC line, a target response built from
// the item, and keywords used to check the learner's spoken/typed answer.
// npcKo / answersKo are Korean translations shown via a "해석 보기" toggle.
// Categories are ordered roughly easy -> harder, so Day 1 starts with simple topics.

const CATEGORY_TEMPLATES = [
  {
    id: "greetings_intro",
    title: "인사와 자기소개",
    npc: "Hi there! I don't think we've met. What's your name?",
    npcKo: "안녕하세요! 저희 처음 뵙는 것 같아요. 이름이 어떻게 되세요?",
    template: (item) => `My name is ${item}. Nice to meet you.`,
    items: ["Alex", "Jordan", "Sam", "Taylor", "Jamie", "Chris", "Morgan", "Casey", "Riley", "Drew",
      "Min-jun", "Ji-woo", "Seo-yeon", "Do-yoon", "Ha-eun", "Yu-jin", "Joon-ho", "Eun-ji", "Tae-yang", "Su-bin"],
    answersKo: ["제 이름은 Alex예요. 만나서 반가워요.", "제 이름은 Jordan이에요. 만나서 반가워요.",
      "제 이름은 Sam이에요. 만나서 반가워요.", "제 이름은 Taylor예요. 만나서 반가워요.",
      "제 이름은 Jamie예요. 만나서 반가워요.", "제 이름은 Chris예요. 만나서 반가워요.",
      "제 이름은 Morgan이에요. 만나서 반가워요.", "제 이름은 Casey예요. 만나서 반가워요.",
      "제 이름은 Riley예요. 만나서 반가워요.", "제 이름은 Drew예요. 만나서 반가워요.",
      "제 이름은 민준이에요. 만나서 반가워요.", "제 이름은 지우예요. 만나서 반가워요.",
      "제 이름은 서연이에요. 만나서 반가워요.", "제 이름은 도윤이에요. 만나서 반가워요.",
      "제 이름은 하은이에요. 만나서 반가워요.", "제 이름은 유진이에요. 만나서 반가워요.",
      "제 이름은 준호예요. 만나서 반가워요.", "제 이름은 은지예요. 만나서 반가워요.",
      "제 이름은 태양이에요. 만나서 반가워요.", "제 이름은 수빈이에요. 만나서 반가워요."],
  },
  {
    id: "smalltalk_weather",
    title: "날씨 스몰토크",
    npc: "Quite a day out there, isn't it? What do you think of the weather?",
    npcKo: "오늘 날씨가 좀 그렇죠? 날씨에 대해 어떻게 생각하세요?",
    template: (item) => `It's ${item} today, isn't it?`,
    items: ["sunny", "cloudy", "rainy", "windy", "freezing", "humid", "chilly", "warm", "snowing", "foggy",
      "boiling hot", "pretty mild", "getting colder", "clearing up", "about to rain", "really nice",
      "a bit gloomy", "perfect for a walk", "unusually dry", "storming"],
    answersKo: ["오늘 화창하네요, 그렇죠?", "오늘 흐리네요, 그렇죠?", "오늘 비가 오네요, 그렇죠?",
      "오늘 바람이 부네요, 그렇죠?", "오늘 엄청 춥네요, 그렇죠?", "오늘 습하네요, 그렇죠?",
      "오늘 쌀쌀하네요, 그렇죠?", "오늘 따뜻하네요, 그렇죠?", "오늘 눈이 오네요, 그렇죠?",
      "오늘 안개가 꼈네요, 그렇죠?", "오늘 엄청 덥네요, 그렇죠?", "오늘 꽤 포근하네요, 그렇죠?",
      "점점 추워지고 있네요, 그렇죠?", "날이 개고 있네요, 그렇죠?", "곧 비가 올 것 같네요, 그렇죠?",
      "오늘 정말 좋네요, 그렇죠?", "오늘 좀 흐릿하네요, 그렇죠?", "산책하기 딱 좋은 날씨네요, 그렇죠?",
      "유난히 건조하네요, 그렇죠?", "폭풍이 몰아치네요, 그렇죠?"],
  },
  {
    id: "smalltalk_weekend",
    title: "주말 이야기",
    npc: "So, any plans for the weekend?",
    npcKo: "이번 주말에 무슨 계획 있으세요?",
    template: (item) => `I'm planning to ${item} this weekend.`,
    items: ["go hiking", "watch a movie", "visit my family", "clean my apartment", "go grocery shopping",
      "meet some friends", "relax at home", "go to the gym", "read a book", "try a new restaurant",
      "go to the beach", "work on a project", "take a day trip", "go camping", "play video games",
      "go cycling", "cook a big meal", "catch up on sleep", "go to a concert", "do some gardening"],
    answersKo: ["이번 주말에 등산 갈 계획이에요.", "이번 주말에 영화 볼 계획이에요.",
      "이번 주말에 가족을 만나러 갈 계획이에요.", "이번 주말에 집 청소할 계획이에요.",
      "이번 주말에 장 보러 갈 계획이에요.", "이번 주말에 친구들을 만날 계획이에요.",
      "이번 주말에 집에서 쉴 계획이에요.", "이번 주말에 헬스장에 갈 계획이에요.",
      "이번 주말에 책을 읽을 계획이에요.", "이번 주말에 새로운 식당에 가볼 계획이에요.",
      "이번 주말에 해변에 갈 계획이에요.", "이번 주말에 프로젝트를 할 계획이에요.",
      "이번 주말에 당일치기 여행을 갈 계획이에요.", "이번 주말에 캠핑 갈 계획이에요.",
      "이번 주말에 비디오 게임을 할 계획이에요.", "이번 주말에 자전거를 탈 계획이에요.",
      "이번 주말에 거하게 요리할 계획이에요.", "이번 주말에 밀린 잠을 잘 계획이에요.",
      "이번 주말에 콘서트에 갈 계획이에요.", "이번 주말에 정원을 가꿀 계획이에요."],
  },
  {
    id: "smalltalk_hobby",
    title: "취미 이야기",
    npc: "What do you like to do in your free time?",
    npcKo: "쉬는 시간에는 주로 뭐 하세요?",
    template: (item) => `In my free time, I like to ${item}.`,
    items: ["play guitar", "paint", "go running", "play basketball", "bake", "knit", "play chess",
      "take photos", "write in a journal", "go fishing", "watch documentaries", "play the piano",
      "do yoga", "collect stamps", "garden", "play board games", "swim", "go rock climbing",
      "learn languages", "build models"],
    answersKo: ["쉬는 시간에는 기타 치는 걸 좋아해요.", "쉬는 시간에는 그림 그리는 걸 좋아해요.",
      "쉬는 시간에는 달리기 하는 걸 좋아해요.", "쉬는 시간에는 농구 하는 걸 좋아해요.",
      "쉬는 시간에는 빵 굽는 걸 좋아해요.", "쉬는 시간에는 뜨개질 하는 걸 좋아해요.",
      "쉬는 시간에는 체스 두는 걸 좋아해요.", "쉬는 시간에는 사진 찍는 걸 좋아해요.",
      "쉬는 시간에는 일기 쓰는 걸 좋아해요.", "쉬는 시간에는 낚시 하는 걸 좋아해요.",
      "쉬는 시간에는 다큐멘터리 보는 걸 좋아해요.", "쉬는 시간에는 피아노 치는 걸 좋아해요.",
      "쉬는 시간에는 요가 하는 걸 좋아해요.", "쉬는 시간에는 우표 모으는 걸 좋아해요.",
      "쉬는 시간에는 정원 가꾸는 걸 좋아해요.", "쉬는 시간에는 보드게임 하는 걸 좋아해요.",
      "쉬는 시간에는 수영 하는 걸 좋아해요.", "쉬는 시간에는 클라이밍 하는 걸 좋아해요.",
      "쉬는 시간에는 외국어 배우는 걸 좋아해요.", "쉬는 시간에는 모형 만드는 걸 좋아해요."],
  },
  {
    id: "smalltalk_family",
    title: "가족 이야기",
    npc: "Do you have any brothers or sisters?",
    npcKo: "형제자매 있으세요?",
    template: (item) => `Yes, I have ${item}.`,
    items: ["an older brother", "a younger sister", "two older sisters", "one younger brother",
      "twin siblings", "three siblings", "no siblings, I'm an only child", "a brother and a sister",
      "a big family with four kids", "just one younger sister", "an older brother and a younger brother",
      "two brothers", "a half-sister", "a stepbrother", "a large extended family nearby",
      "one sibling who lives abroad", "a sister who's a doctor", "a brother in college",
      "cousins who live close by", "grandparents living with us"],
    answersKo: ["네, 형이(오빠가) 한 명 있어요.", "네, 여동생이 한 명 있어요.",
      "네, 언니가(누나가) 두 명 있어요.", "네, 남동생이 한 명 있어요.",
      "네, 쌍둥이 형제자매가 있어요.", "네, 형제자매가 세 명 있어요.",
      "아니요, 저는 외동이에요.", "네, 오빠 한 명과 여동생 한 명이 있어요.",
      "네, 아이가 넷인 대가족이에요.", "네, 여동생이 딱 한 명 있어요.",
      "네, 형 한 명과 남동생 한 명이 있어요.", "네, 남자 형제가 두 명 있어요.",
      "네, 배다른 여동생이 한 명 있어요.", "네, 의붓형제가 한 명 있어요.",
      "네, 근처에 대가족이 살아요.", "네, 해외에 사는 형제자매가 한 명 있어요.",
      "네, 의사인 언니(누나)가 있어요.", "네, 대학 다니는 형(오빠)이 있어요.",
      "네, 가까이 사는 사촌들이 있어요.", "네, 조부모님과 함께 살아요."],
  },
  {
    id: "making_plans",
    title: "약속 잡기",
    npc: "Are you free sometime this week? Want to grab a bite?",
    npcKo: "이번 주에 시간 되세요? 같이 식사할까요?",
    template: (item) => `Sure, how about ${item}?`,
    items: ["Monday evening", "Tuesday at noon", "Wednesday after work", "Thursday morning",
      "Friday night", "Saturday afternoon", "Sunday brunch", "tomorrow at 7", "next Monday",
      "later this week", "this weekend", "early next week", "Thursday at lunchtime",
      "Friday around 6", "Saturday evening", "sometime Wednesday", "Tuesday evening",
      "the day after tomorrow", "this coming Sunday", "whenever works for you"],
    answersKo: ["좋아요, 월요일 저녁 어때요?", "좋아요, 화요일 정오 어때요?",
      "좋아요, 수요일 퇴근 후 어때요?", "좋아요, 목요일 아침 어때요?",
      "좋아요, 금요일 저녁 어때요?", "좋아요, 토요일 오후 어때요?",
      "좋아요, 일요일 브런치 어때요?", "좋아요, 내일 7시 어때요?",
      "좋아요, 다음 주 월요일 어때요?", "좋아요, 이번 주 후반 어때요?",
      "좋아요, 이번 주말 어때요?", "좋아요, 다음 주 초 어때요?",
      "좋아요, 목요일 점심시간 어때요?", "좋아요, 금요일 6시쯤 어때요?",
      "좋아요, 토요일 저녁 어때요?", "좋아요, 수요일 중으로 어때요?",
      "좋아요, 화요일 저녁 어때요?", "좋아요, 모레 어때요?",
      "좋아요, 이번 주 일요일 어때요?", "좋아요, 편하신 아무 때나 어때요?"],
  },
  {
    id: "coffee_order",
    title: "카페에서 음료 주문하기",
    npc: "Hi! What can I get started for you today?",
    npcKo: "안녕하세요! 오늘 뭐로 시작해드릴까요?",
    template: (item) => `I'll have ${item}, please.`,
    items: ["a latte", "a cappuccino", "an iced americano", "a hot chocolate", "an espresso",
      "a cold brew", "a mocha", "a green tea", "a chai latte", "a caramel macchiato",
      "a flat white", "an iced tea", "a hazelnut latte", "a decaf coffee", "a matcha latte",
      "an affogato", "a vanilla latte", "a black coffee", "a frappuccino", "a lemonade"],
    answersKo: ["라떼 주세요.", "카푸치노 주세요.", "아이스 아메리카노 주세요.", "핫초코 주세요.",
      "에스프레소 주세요.", "콜드브루 주세요.", "모카 주세요.", "녹차 주세요.",
      "차이 라떼 주세요.", "카라멜 마키아토 주세요.", "플랫 화이트 주세요.", "아이스티 주세요.",
      "헤이즐넛 라떼 주세요.", "디카페인 커피 주세요.", "말차 라떼 주세요.", "아포가토 주세요.",
      "바닐라 라떼 주세요.", "블랙커피 주세요.", "프라푸치노 주세요.", "레모네이드 주세요."],
  },
  {
    id: "fastfood_order",
    title: "패스트푸드 주문하기",
    npc: "Welcome! What would you like to order today?",
    npcKo: "어서오세요! 오늘 뭘 주문하시겠어요?",
    template: (item) => `Can I get ${item}, please?`,
    items: ["a cheeseburger", "a chicken sandwich", "a large fries", "a fish burger", "a veggie burger",
      "a small soda", "chicken nuggets", "onion rings", "a hot dog", "a taco combo",
      "a burrito bowl", "a slice of pizza", "a milkshake", "a salad", "a wrap",
      "a bacon burger", "a double cheeseburger meal", "an ice cream cone", "a fried chicken combo",
      "a value meal"],
    answersKo: ["치즈버거 주세요.", "치킨 샌드위치 주세요.", "라지 감자튀김 주세요.", "피시버거 주세요.",
      "채소버거 주세요.", "콜라 작은 사이즈 주세요.", "치킨 너겟 주세요.", "어니언링 주세요.",
      "핫도그 주세요.", "타코 세트 주세요.", "부리토 볼 주세요.", "피자 한 조각 주세요.",
      "밀크셰이크 주세요.", "샐러드 주세요.", "랩 주세요.", "베이컨버거 주세요.",
      "더블 치즈버거 세트 주세요.", "아이스크림콘 주세요.", "프라이드치킨 세트 주세요.", "밸류밀 주세요."],
  },
  {
    id: "restaurant_order",
    title: "레스토랑에서 메뉴 주문",
    npc: "Are you ready to order? What would you like today?",
    npcKo: "주문하시겠어요? 오늘 뭘로 하시겠어요?",
    template: (item) => `I'll have the ${item}, please.`,
    items: ["grilled salmon", "steak", "pasta carbonara", "Caesar salad", "mushroom risotto",
      "roast chicken", "fish and chips", "vegetable curry", "lamb chops", "seafood pasta",
      "beef stew", "tomato soup", "duck breast", "pork ribs", "grilled shrimp",
      "spaghetti bolognese", "margherita pizza", "shrimp tacos", "chicken parmesan", "vegetable stir-fry"],
    answersKo: ["구운 연어로 할게요.", "스테이크로 할게요.", "파스타 카르보나라로 할게요.",
      "시저 샐러드로 할게요.", "버섯 리조또로 할게요.", "로스트 치킨으로 할게요.",
      "피시 앤 칩스로 할게요.", "채소 커리로 할게요.", "양갈비로 할게요.", "해산물 파스타로 할게요.",
      "소고기 스튜로 할게요.", "토마토 수프로 할게요.", "오리가슴살로 할게요.", "돼지 갈비로 할게요.",
      "구운 새우로 할게요.", "스파게티 볼로네제로 할게요.", "마르게리타 피자로 할게요.",
      "새우 타코로 할게요.", "치킨 파마산으로 할게요.", "채소 볶음으로 할게요."],
  },
  {
    id: "directions_ask",
    title: "길 물어보기",
    npc: "Excuse me, could I ask you something?",
    npcKo: "실례합니다, 뭐 좀 여쭤봐도 될까요?",
    template: (item) => `Could you tell me how to get to ${item}?`,
    items: ["the nearest subway station", "the bus stop", "the train station", "the post office",
      "the closest pharmacy", "city hall", "the museum", "the shopping mall", "the airport",
      "the nearest bank", "the library", "the hospital", "the police station", "the park",
      "the nearest gas station", "the beach", "the stadium", "the university", "the market",
      "downtown"],
    answersKo: ["가장 가까운 지하철역에 어떻게 가는지 알려주시겠어요?", "버스 정류장에 어떻게 가는지 알려주시겠어요?",
      "기차역에 어떻게 가는지 알려주시겠어요?", "우체국에 어떻게 가는지 알려주시겠어요?",
      "가장 가까운 약국에 어떻게 가는지 알려주시겠어요?", "시청에 어떻게 가는지 알려주시겠어요?",
      "박물관에 어떻게 가는지 알려주시겠어요?", "쇼핑몰에 어떻게 가는지 알려주시겠어요?",
      "공항에 어떻게 가는지 알려주시겠어요?", "가장 가까운 은행에 어떻게 가는지 알려주시겠어요?",
      "도서관에 어떻게 가는지 알려주시겠어요?", "병원에 어떻게 가는지 알려주시겠어요?",
      "경찰서에 어떻게 가는지 알려주시겠어요?", "공원에 어떻게 가는지 알려주시겠어요?",
      "가장 가까운 주유소에 어떻게 가는지 알려주시겠어요?", "해변에 어떻게 가는지 알려주시겠어요?",
      "경기장에 어떻게 가는지 알려주시겠어요?", "대학교에 어떻게 가는지 알려주시겠어요?",
      "시장에 어떻게 가는지 알려주시겠어요?", "시내(다운타운)에 어떻게 가는지 알려주시겠어요?"],
  },
  {
    id: "give_directions",
    title: "길 알려주기",
    npc: "Excuse me, do you know where the nearest station is?",
    npcKo: "실례합니다, 가장 가까운 역이 어디인지 아세요?",
    template: (item) => `Sure, go straight and ${item}.`,
    items: ["turn left at the corner", "turn right at the light", "it's on your right",
      "it's just across the street", "go past the bank", "take the second left",
      "it's two blocks down", "follow this road for five minutes", "it's next to the bakery",
      "cross the street and it's there", "go up the hill", "it's behind the church",
      "take the elevator to the second floor", "it's right next to the entrance",
      "go through the park", "it's at the end of this street", "keep walking straight",
      "take the first right", "it's opposite the cafe", "it's a five-minute walk from here"],
    answersKo: ["네, 직진하다가 모퉁이에서 왼쪽으로 도세요.", "네, 직진하다가 신호등에서 오른쪽으로 도세요.",
      "네, 직진하면 오른쪽에 있어요.", "네, 직진하면 길 건너 바로예요.",
      "네, 직진하다가 은행을 지나세요.", "네, 직진하다가 두 번째 왼쪽으로 도세요.",
      "네, 직진해서 두 블록 가세요.", "네, 이 길을 따라 5분 정도 가세요.",
      "네, 직진하면 빵집 옆에 있어요.", "네, 길을 건너면 바로 거기예요.",
      "네, 직진하다가 언덕 위로 올라가세요.", "네, 직진하면 교회 뒤쪽에 있어요.",
      "네, 엘리베이터 타고 2층으로 가세요.", "네, 직진하면 입구 바로 옆이에요.",
      "네, 공원을 가로질러 가세요.", "네, 이 길 끝에 있어요.",
      "네, 계속 직진하세요.", "네, 첫 번째 오른쪽으로 도세요.",
      "네, 카페 맞은편에 있어요.", "네, 여기서 걸어서 5분 거리예요."],
  },
  {
    id: "taxi_destination",
    title: "택시 타기",
    npc: "Where to?",
    npcKo: "어디로 모실까요?",
    template: (item) => `${item}, please.`,
    items: ["The airport", "Downtown, near the city hall", "This address, please",
      "The Grand Hotel", "The central train station", "The nearest hospital",
      "123 Main Street", "The convention center", "The shopping district",
      "The university campus", "The ferry terminal", "Riverside Park",
      "The stadium", "The old town", "The business district",
      "The bus terminal", "That building over there", "The nearest subway entrance",
      "The harbor", "Just around the corner"],
    answersKo: ["공항으로 가주세요.", "시청 근처 시내로 가주세요.", "이 주소로 가주세요.",
      "그랜드 호텔로 가주세요.", "중앙역으로 가주세요.", "가장 가까운 병원으로 가주세요.",
      "메인스트리트 123번지로 가주세요.", "컨벤션 센터로 가주세요.", "쇼핑 지구로 가주세요.",
      "대학 캠퍼스로 가주세요.", "여객터미널로 가주세요.", "리버사이드 공원으로 가주세요.",
      "경기장으로 가주세요.", "구시가지로 가주세요.", "비즈니스 지구로 가주세요.",
      "버스 터미널로 가주세요.", "저기 저 건물로 가주세요.", "가장 가까운 지하철 입구로 가주세요.",
      "항구로 가주세요.", "바로 이 모퉁이로 가주세요."],
  },
  {
    id: "bus_ask",
    title: "버스 이용하기",
    npc: "Can I help you find a bus?",
    npcKo: "버스 찾으시는 거 도와드릴까요?",
    template: (item) => `Does this bus go to ${item}?`,
    items: ["downtown", "the airport", "the train station", "city hall", "the university",
      "the shopping mall", "the beach", "the stadium", "the hospital", "the museum",
      "the market", "the harbor", "the old town", "the business district", "the park",
      "the library", "the convention center", "the zoo", "the botanical garden", "the ferry terminal"],
    answersKo: ["이 버스 시내로 가나요?", "이 버스 공항으로 가나요?", "이 버스 기차역으로 가나요?",
      "이 버스 시청으로 가나요?", "이 버스 대학교로 가나요?", "이 버스 쇼핑몰로 가나요?",
      "이 버스 해변으로 가나요?", "이 버스 경기장으로 가나요?", "이 버스 병원으로 가나요?",
      "이 버스 박물관으로 가나요?", "이 버스 시장으로 가나요?", "이 버스 항구로 가나요?",
      "이 버스 구시가지로 가나요?", "이 버스 비즈니스 지구로 가나요?", "이 버스 공원으로 가나요?",
      "이 버스 도서관으로 가나요?", "이 버스 컨벤션 센터로 가나요?", "이 버스 동물원으로 가나요?",
      "이 버스 식물원으로 가나요?", "이 버스 여객터미널로 가나요?"],
  },
  {
    id: "subway_ask",
    title: "지하철 이용하기",
    npc: "Excuse me, do you know which line I need?",
    npcKo: "실례합니다, 제가 몇 호선을 타야 하는지 아세요?",
    template: (item) => `You'll need to take ${item}.`,
    items: ["the red line", "the blue line", "line 2", "the green line", "line 5",
      "the express train", "the yellow line", "line 3, then transfer at Central",
      "the orange line", "the airport line", "line 1 toward downtown", "the purple line",
      "the circle line", "line 4, two stops from here", "the local train, not the express",
      "the blue line, then walk five minutes", "line 7", "the north-bound line",
      "the last train of the night", "any train heading downtown"],
    answersKo: ["빨간 노선을 타셔야 해요.", "파란 노선을 타셔야 해요.", "2호선을 타셔야 해요.",
      "초록 노선을 타셔야 해요.", "5호선을 타셔야 해요.", "급행열차를 타셔야 해요.",
      "노란 노선을 타셔야 해요.", "3호선을 타고 센트럴에서 환승하셔야 해요.", "주황 노선을 타셔야 해요.",
      "공항선을 타셔야 해요.", "시내 방면 1호선을 타셔야 해요.", "보라 노선을 타셔야 해요.",
      "순환선을 타셔야 해요.", "4호선을 타고 두 정거장 가셔야 해요.", "급행 말고 완행열차를 타셔야 해요.",
      "파란 노선을 타고 5분 정도 걸으셔야 해요.", "7호선을 타셔야 해요.", "북쪽 방면 노선을 타셔야 해요.",
      "막차를 타셔야 해요.", "시내로 가는 아무 열차나 타셔야 해요."],
  },
  {
    id: "hotel_checkin",
    title: "호텔 체크인",
    npc: "Welcome! Do you have a reservation with us?",
    npcKo: "어서오세요! 예약하셨나요?",
    template: (item) => `Yes, I booked ${item}.`,
    items: ["a single room", "a double room", "a room with a city view", "a room with two beds",
      "a suite for two nights", "a non-smoking room", "a room on a high floor", "a deluxe room",
      "a room with breakfast included", "an ocean view room", "a family room",
      "a room for three nights", "a king-size room", "an early check-in",
      "a room near the elevator", "a quiet room", "a room with a balcony",
      "a twin room", "a room under my company's name", "a late check-out"],
    answersKo: ["네, 싱글룸을 예약했어요.", "네, 더블룸을 예약했어요.", "네, 시티뷰 방을 예약했어요.",
      "네, 침대 두 개인 방을 예약했어요.", "네, 2박 스위트룸을 예약했어요.", "네, 금연실을 예약했어요.",
      "네, 높은 층 방을 예약했어요.", "네, 디럭스룸을 예약했어요.", "네, 조식 포함 방을 예약했어요.",
      "네, 오션뷰 방을 예약했어요.", "네, 패밀리룸을 예약했어요.", "네, 3박 방을 예약했어요.",
      "네, 킹사이즈 방을 예약했어요.", "네, 얼리체크인을 예약했어요.", "네, 엘리베이터 근처 방을 예약했어요.",
      "네, 조용한 방을 예약했어요.", "네, 발코니 있는 방을 예약했어요.", "네, 트윈룸을 예약했어요.",
      "네, 회사 이름으로 예약했어요.", "네, 레이트 체크아웃을 예약했어요."],
  },
  {
    id: "hotel_roomservice",
    title: "호텔 룸서비스",
    npc: "Room service, how can I help you?",
    npcKo: "룸서비스입니다, 무엇을 도와드릴까요?",
    template: (item) => `Could you send up ${item}?`,
    items: ["some extra towels", "a bottle of water", "breakfast for two", "an extra pillow",
      "a wake-up call at 7", "a hair dryer", "some coffee", "an iron and ironing board",
      "extra toiletries", "a blanket", "some ice", "a menu", "a toothbrush",
      "slippers", "a laundry bag", "the newspaper", "a charger cable",
      "an extra key card", "a late checkout confirmation", "directions to the gym"],
    answersKo: ["수건 좀 더 가져다주시겠어요?", "생수 한 병 가져다주시겠어요?", "2인 조식 가져다주시겠어요?",
      "베개 하나 더 가져다주시겠어요?", "7시에 모닝콜 해주시겠어요?", "헤어드라이어 가져다주시겠어요?",
      "커피 좀 가져다주시겠어요?", "다리미와 다리미판 가져다주시겠어요?", "세면용품 좀 더 가져다주시겠어요?",
      "담요 가져다주시겠어요?", "얼음 좀 가져다주시겠어요?", "메뉴판 가져다주시겠어요?",
      "칫솔 가져다주시겠어요?", "슬리퍼 가져다주시겠어요?", "세탁 봉투 가져다주시겠어요?",
      "신문 가져다주시겠어요?", "충전 케이블 가져다주시겠어요?", "키카드 하나 더 가져다주시겠어요?",
      "레이트 체크아웃 확인해 주시겠어요?", "헬스장 가는 길 알려주시겠어요?"],
  },
  {
    id: "hotel_checkout",
    title: "호텔 체크아웃",
    npc: "Good morning! Checking out today?",
    npcKo: "좋은 아침입니다! 오늘 체크아웃하시나요?",
    template: (item) => `Yes, and could you also ${item}?`,
    items: ["print my receipt", "check my minibar charges", "call a taxi for me",
      "hold my luggage until 3pm", "arrange a late checkout", "confirm the total on my card",
      "check if I have any pending charges", "help me with my bags",
      "give me a copy of the invoice", "double check my checkout time",
      "recommend a place for breakfast nearby", "store my bags for a few hours",
      "tell me how to get to the airport", "confirm my refund for the extra night",
      "check me out from room 402", "provide a taxi voucher",
      "verify there's no outstanding balance", "print a copy for my company",
      "check if the shuttle is still running", "let the manager know I enjoyed my stay"],
    answersKo: ["네, 그리고 영수증도 출력해 주시겠어요?", "네, 그리고 미니바 이용요금도 확인해 주시겠어요?",
      "네, 그리고 택시도 불러주시겠어요?", "네, 그리고 짐을 3시까지 맡아주시겠어요?",
      "네, 그리고 레이트 체크아웃도 해주시겠어요?", "네, 그리고 카드 결제 총액도 확인해 주시겠어요?",
      "네, 그리고 미결제 요금이 있는지 확인해 주시겠어요?", "네, 그리고 짐 옮기는 것도 도와주시겠어요?",
      "네, 그리고 청구서 사본도 주시겠어요?", "네, 그리고 체크아웃 시간도 다시 확인해 주시겠어요?",
      "네, 그리고 근처 조식 맛집도 추천해 주시겠어요?", "네, 그리고 짐을 몇 시간 맡아주시겠어요?",
      "네, 그리고 공항 가는 길도 알려주시겠어요?", "네, 그리고 추가 숙박료 환불도 확인해 주시겠어요?",
      "네, 402호 체크아웃 처리해 주시겠어요?", "네, 그리고 택시 바우처도 주시겠어요?",
      "네, 그리고 미결제 잔액이 없는지 확인해 주시겠어요?", "네, 그리고 회사용 사본도 출력해 주시겠어요?",
      "네, 그리고 셔틀버스가 아직 운행하는지 확인해 주시겠어요?", "네, 그리고 매니저님께 잘 지냈다고 전해주시겠어요?"],
  },
  {
    id: "airport_checkin",
    title: "공항 체크인",
    npc: "Good morning! May I see your passport and ticket, please?",
    npcKo: "좋은 아침입니다! 여권과 항공권 좀 보여주시겠어요?",
    template: (item) => `Sure, and I'd like ${item}.`,
    items: ["a window seat", "an aisle seat", "to check one bag", "to check two bags",
      "an extra legroom seat", "a seat near the front", "a seat next to my friend",
      "to upgrade to business class", "a vegetarian meal", "to confirm my connecting flight",
      "an earlier flight if possible", "a seat away from the emergency exit",
      "to add my frequent flyer number", "a boarding pass printed, please",
      "a seat with more legroom", "to check my carry-on due to its size",
      "a seat toward the back", "priority boarding", "to confirm my baggage allowance",
      "to know my gate number"],
    answersKo: ["네, 그리고 창가 좌석으로 부탁드려요.", "네, 그리고 통로 좌석으로 부탁드려요.",
      "네, 그리고 가방 한 개 부칠게요.", "네, 그리고 가방 두 개 부칠게요.",
      "네, 그리고 다리 공간 넓은 좌석으로 부탁드려요.", "네, 그리고 앞쪽 좌석으로 부탁드려요.",
      "네, 그리고 친구 옆자리로 부탁드려요.", "네, 그리고 비즈니스석으로 업그레이드하고 싶어요.",
      "네, 그리고 채식 기내식으로 부탁드려요.", "네, 그리고 연결편 확인 좀 해주시겠어요.",
      "네, 그리고 가능하면 더 이른 비행기로 부탁드려요.", "네, 그리고 비상구 좌석은 피해서 부탁드려요.",
      "네, 그리고 마일리지 번호도 추가해 주세요.", "네, 그리고 탑승권 출력해 주시겠어요.",
      "네, 그리고 다리 공간 넓은 좌석으로 부탁드려요.", "네, 그리고 크기 때문에 이 캐리어는 부쳐야 할 것 같아요.",
      "네, 그리고 뒤쪽 좌석으로 부탁드려요.", "네, 그리고 우선 탑승으로 부탁드려요.",
      "네, 그리고 수하물 허용량도 확인해 주시겠어요.", "네, 그리고 게이트 번호도 알려주시겠어요."],
  },
  {
    id: "airport_security",
    title: "공항 보안검색",
    npc: "Please place your belongings in the tray. Do you have any electronics or liquids?",
    npcKo: "소지품을 트레이에 올려주세요. 전자기기나 액체류 있으신가요?",
    template: (item) => `Yes, I have ${item}.`,
    items: ["a laptop", "a tablet", "a small bottle of water", "some liquid medicine",
      "a phone charger", "a camera", "duty-free perfume", "a power bank",
      "a bottle of sunscreen under 100ml", "a pair of headphones", "a portable fan",
      "some snacks", "a laptop and a tablet", "contact lens solution",
      "an electric razor", "a small umbrella", "a book and a laptop",
      "nothing to declare", "a spare battery", "prescription medicine"],
    answersKo: ["네, 노트북이 있어요.", "네, 태블릿이 있어요.", "네, 작은 생수병이 있어요.",
      "네, 액체 약이 있어요.", "네, 휴대폰 충전기가 있어요.", "네, 카메라가 있어요.",
      "네, 면세 향수가 있어요.", "네, 보조배터리가 있어요.", "네, 100ml 이하 선크림이 있어요.",
      "네, 헤드폰이 있어요.", "네, 휴대용 선풍기가 있어요.", "네, 간식이 좀 있어요.",
      "네, 노트북과 태블릿이 있어요.", "네, 렌즈 세정액이 있어요.", "네, 전기 면도기가 있어요.",
      "네, 작은 우산이 있어요.", "네, 책과 노트북이 있어요.", "신고할 게 없어요.",
      "네, 여분 배터리가 있어요.", "네, 처방약이 있어요."],
  },
  {
    id: "airport_immigration",
    title: "공항 입국심사",
    npc: "What's the purpose of your visit?",
    npcKo: "방문 목적이 어떻게 되세요?",
    template: (item) => `I'm here for ${item}.`,
    items: ["vacation", "business", "a conference", "visiting family", "a study exchange",
      "sightseeing", "a short work trip", "a wedding", "a friend's graduation",
      "a language course", "a job interview", "a music festival", "medical treatment",
      "an internship", "a layover", "volunteer work", "a research project",
      "a honeymoon", "a school trip", "attending a workshop"],
    answersKo: ["휴가로 왔어요.", "업무로 왔어요.", "컨퍼런스 때문에 왔어요.", "가족 방문차 왔어요.",
      "교환학생 프로그램으로 왔어요.", "관광하러 왔어요.", "짧은 출장으로 왔어요.", "결혼식 때문에 왔어요.",
      "친구 졸업식 때문에 왔어요.", "어학연수로 왔어요.", "면접 때문에 왔어요.", "음악 페스티벌 때문에 왔어요.",
      "치료 목적으로 왔어요.", "인턴십으로 왔어요.", "경유차 왔어요.", "봉사활동 하러 왔어요.",
      "연구 프로젝트 때문에 왔어요.", "신혼여행으로 왔어요.", "수학여행으로 왔어요.", "워크숍 참석차 왔어요."],
  },
  {
    id: "carrental_pickup",
    title: "렌터카 빌리기",
    npc: "Hi! What kind of car are you looking for today?",
    npcKo: "안녕하세요! 오늘 어떤 차를 찾으세요?",
    template: (item) => `I'd like to rent ${item}.`,
    items: ["a compact car", "an SUV", "a sedan", "a car with automatic transmission",
      "a car with GPS", "a minivan", "a hybrid car", "the cheapest option available",
      "a car for one week", "a car with a child seat", "an electric car",
      "a convertible", "a car with unlimited mileage", "a four-wheel drive",
      "a car with extra insurance", "a car for a one-way trip", "a luxury car",
      "a car that seats seven", "a fuel-efficient car", "a car with a roof rack"],
    answersKo: ["소형차를 빌리고 싶어요.", "SUV를 빌리고 싶어요.", "세단을 빌리고 싶어요.",
      "자동변속기 차를 빌리고 싶어요.", "내비게이션 있는 차를 빌리고 싶어요.", "미니밴을 빌리고 싶어요.",
      "하이브리드 차를 빌리고 싶어요.", "가장 저렴한 옵션으로 빌리고 싶어요.", "일주일 동안 빌리고 싶어요.",
      "카시트 있는 차를 빌리고 싶어요.", "전기차를 빌리고 싶어요.", "컨버터블을 빌리고 싶어요.",
      "주행거리 무제한 차를 빌리고 싶어요.", "사륜구동 차를 빌리고 싶어요.", "추가 보험 포함 차를 빌리고 싶어요.",
      "편도 여행용 차를 빌리고 싶어요.", "고급 차를 빌리고 싶어요.", "7인승 차를 빌리고 싶어요.",
      "연비 좋은 차를 빌리고 싶어요.", "루프랙 있는 차를 빌리고 싶어요."],
  },
  {
    id: "carrental_return",
    title: "렌터카 반납하기",
    npc: "Are you returning the car today? Let me check a few things.",
    npcKo: "오늘 차 반납하시는 거죠? 몇 가지만 확인할게요.",
    template: (item) => `Yes, and I made sure to ${item}.`,
    items: ["fill up the gas tank", "clean out my belongings", "check the tire pressure",
      "keep all the original documents", "return it on time", "note the mileage",
      "check for any damage beforehand", "bring both sets of keys",
      "empty the trunk", "return it to the same location", "remove my GPS device",
      "double check the insurance papers", "take photos of the car",
      "return the parking pass", "check the oil level", "wipe down the interior",
      "confirm the final charge", "bring the rental agreement", "return the charging cable",
      "check I didn't leave anything in the glove compartment"],
    answersKo: ["네, 주유는 가득 채워놨어요.", "네, 짐도 다 챙겼어요.", "네, 타이어 공기압도 확인했어요.",
      "네, 원래 서류도 다 챙겼어요.", "네, 제시간에 반납했어요.", "네, 주행거리도 기록해뒀어요.",
      "네, 미리 손상 여부도 확인했어요.", "네, 키 두 개 다 가져왔어요.", "네, 트렁크도 비웠어요.",
      "네, 같은 지점에 반납했어요.", "네, GPS 장치도 제거했어요.", "네, 보험 서류도 다시 확인했어요.",
      "네, 차 사진도 찍어뒀어요.", "네, 주차권도 반납했어요.", "네, 엔진오일도 확인했어요.",
      "네, 내부도 닦아뒀어요.", "네, 최종 요금도 확인했어요.", "네, 대여 계약서도 가져왔어요.",
      "네, 충전 케이블도 반납했어요.", "네, 글로브박스에 놓고 온 게 없는지도 확인했어요."],
  },
  {
    id: "grocery_shopping",
    title: "장보기",
    npc: "Hi, can I help you find anything today?",
    npcKo: "안녕하세요, 오늘 찾으시는 거 도와드릴까요?",
    template: (item) => `Yes, where can I find ${item}?`,
    items: ["fresh vegetables", "milk", "eggs", "bread", "chicken breast",
      "olive oil", "rice", "pasta", "canned tomatoes", "cereal",
      "frozen vegetables", "yogurt", "cheese", "coffee beans", "spices",
      "bottled water", "snacks", "laundry detergent", "paper towels", "toothpaste"],
    answersKo: ["네, 신선한 채소는 어디 있나요?", "네, 우유는 어디 있나요?", "네, 계란은 어디 있나요?",
      "네, 빵은 어디 있나요?", "네, 닭가슴살은 어디 있나요?", "네, 올리브유는 어디 있나요?",
      "네, 쌀은 어디 있나요?", "네, 파스타면은 어디 있나요?", "네, 토마토 캔은 어디 있나요?",
      "네, 시리얼은 어디 있나요?", "네, 냉동채소는 어디 있나요?", "네, 요거트는 어디 있나요?",
      "네, 치즈는 어디 있나요?", "네, 원두는 어디 있나요?", "네, 향신료는 어디 있나요?",
      "네, 생수는 어디 있나요?", "네, 과자는 어디 있나요?", "네, 세탁세제는 어디 있나요?",
      "네, 키친타월은 어디 있나요?", "네, 치약은 어디 있나요?"],
  },
  {
    id: "clothes_shopping",
    title: "옷 쇼핑하기",
    npc: "Let me know if you need any help finding your size.",
    npcKo: "사이즈 찾으시는 거 있으면 말씀해 주세요.",
    template: (item) => `Actually, could I try on ${item}?`,
    items: ["this in a medium", "a smaller size", "a larger size", "this jacket in blue",
      "these jeans in a 32", "this shirt in white", "a different color",
      "this dress in size 8", "these shoes in a 9", "a size up",
      "this sweater in gray", "the same style in black", "this coat in medium",
      "a size small", "this in extra large", "the one in the window",
      "this skirt in size 6", "a size down", "these pants hemmed shorter",
      "this hat, just to see how it looks"],
    answersKo: ["이거 미디엄 사이즈로 입어봐도 될까요?", "한 치수 작은 걸로 입어봐도 될까요?",
      "한 치수 큰 걸로 입어봐도 될까요?", "이 재킷 파란색으로 입어봐도 될까요?",
      "이 청바지 32 사이즈로 입어봐도 될까요?", "이 셔츠 흰색으로 입어봐도 될까요?",
      "다른 색상으로 입어봐도 될까요?", "이 원피스 8 사이즈로 입어봐도 될까요?",
      "이 신발 9 사이즈로 신어봐도 될까요?", "한 치수 큰 걸로 입어봐도 될까요?",
      "이 스웨터 회색으로 입어봐도 될까요?", "같은 스타일 검정색으로 입어봐도 될까요?",
      "이 코트 미디엄으로 입어봐도 될까요?", "스몰 사이즈로 입어봐도 될까요?",
      "엑스라지로 입어봐도 될까요?", "진열대에 있는 걸로 입어봐도 될까요?",
      "이 치마 6 사이즈로 입어봐도 될까요?", "한 치수 작은 걸로 입어봐도 될까요?",
      "이 바지 기장 줄여서 입어봐도 될까요?", "이 모자 한번 써봐도 될까요?"],
  },
  {
    id: "shoe_shopping",
    title: "신발 쇼핑하기",
    npc: "What size shoe do you usually wear?",
    npcKo: "신발 사이즈 보통 몇 신으세요?",
    template: (item) => `I usually wear ${item}.`,
    items: ["a size 8", "a size 9", "a size 10", "a size 7", "a size 6.5",
      "a size 42 in European sizing", "a size 38", "a wide fit",
      "a narrow fit", "a size 9.5", "a size 11", "a size 40",
      "whatever fits best, I'm flexible", "a size smaller than usual for this brand",
      "a size larger for running shoes", "size 7 in flats", "size 9 in boots",
      "a half size up", "a size 8 in sandals", "a kids' size 4 for my son"],
    answersKo: ["보통 8 사이즈 신어요.", "보통 9 사이즈 신어요.", "보통 10 사이즈 신어요.",
      "보통 7 사이즈 신어요.", "보통 6.5 사이즈 신어요.", "유럽 사이즈로 42 신어요.",
      "38 사이즈 신어요.", "발볼이 넓은 걸 신어요.", "발볼이 좁은 걸 신어요.", "9.5 사이즈 신어요.",
      "11 사이즈 신어요.", "40 사이즈 신어요.", "딱히 상관없어요, 잘 맞으면 돼요.",
      "이 브랜드는 평소보다 작게 신어요.", "운동화는 좀 더 크게 신어요.", "플랫슈즈는 7 사이즈 신어요.",
      "부츠는 9 사이즈 신어요.", "반 사이즈 크게 신어요.", "샌들은 8 사이즈 신어요.",
      "아들은 키즈 4 사이즈 신어요."],
  },
  {
    id: "returning_item",
    title: "환불/교환하기",
    npc: "Hi, how can I help you today?",
    npcKo: "안녕하세요, 오늘 어떻게 도와드릴까요?",
    template: (item) => `I'd like to return this because ${item}.`,
    items: ["it doesn't fit", "it's the wrong size", "it's damaged", "I changed my mind",
      "it doesn't match the description", "I received the wrong item",
      "it stopped working after one use", "I found a cheaper price elsewhere",
      "it was a duplicate gift", "the color is different from the photo",
      "it's missing a part", "I no longer need it", "it arrived late",
      "the packaging was damaged", "it's not what I ordered",
      "it doesn't work with my other devices", "I'd like a refund instead of store credit",
      "it has a defect", "the size chart was misleading", "I simply don't like it"],
    answersKo: ["이거 안 맞아서 반품하고 싶어요.", "사이즈가 잘못 와서 반품하고 싶어요.",
      "파손돼서 반품하고 싶어요.", "마음이 바뀌어서 반품하고 싶어요.", "설명이랑 달라서 반품하고 싶어요.",
      "다른 상품이 와서 반품하고 싶어요.", "한 번 쓰고 고장 나서 반품하고 싶어요.",
      "다른 데서 더 싸게 팔아서 반품하고 싶어요.", "똑같은 선물을 받아서 반품하고 싶어요.",
      "사진이랑 색이 달라서 반품하고 싶어요.", "부품이 빠져있어서 반품하고 싶어요.",
      "더 이상 필요 없어서 반품하고 싶어요.", "늦게 도착해서 반품하고 싶어요.",
      "포장이 훼손돼서 반품하고 싶어요.", "주문한 게 아니라서 반품하고 싶어요.",
      "다른 기기랑 호환이 안 돼서 반품하고 싶어요.", "적립금 말고 환불받고 싶어서 반품하고 싶어요.",
      "불량이 있어서 반품하고 싶어요.", "사이즈표가 헷갈려서 반품하고 싶어요.", "그냥 마음에 안 들어서 반품하고 싶어요."],
  },
  {
    id: "asking_discount",
    title: "할인 물어보기",
    npc: "Is there anything else I can help you with?",
    npcKo: "더 도와드릴 거 있으세요?",
    template: (item) => `Actually, do you have ${item}?`,
    items: ["any discounts today", "a student discount", "a coupon I could use",
      "any ongoing sales", "a loyalty program", "a discount for buying two",
      "a price match policy", "a senior discount", "any promotions this week",
      "a first-time customer discount", "free shipping options",
      "a bundle deal", "any clearance items", "a way to earn points",
      "a discount if I sign up for the newsletter", "a military discount",
      "a group discount", "seasonal sales", "a referral discount code",
      "a better price if I pay in cash"],
    answersKo: ["혹시 오늘 할인되는 거 있나요?", "학생 할인 되나요?", "쓸 수 있는 쿠폰 있나요?",
      "진행 중인 세일 있나요?", "멤버십 제도 있나요?", "두 개 사면 할인되나요?",
      "가격 비교 보장 제도 있나요?", "경로 할인 되나요?", "이번 주 진행하는 프로모션 있나요?",
      "첫 구매 할인 있나요?", "무료 배송 옵션 있나요?", "묶음 할인 있나요?",
      "땡처리 상품 있나요?", "포인트 적립되나요?", "뉴스레터 가입하면 할인되나요?",
      "군인 할인 되나요?", "단체 할인 되나요?", "시즌 세일 있나요?",
      "추천인 할인 코드 있나요?", "현금으로 내면 더 싸지나요?"],
  },
  {
    id: "checkout_payment",
    title: "계산하기",
    npc: "That'll be everything. How would you like to pay?",
    npcKo: "이게 전부입니다. 결제는 어떻게 하시겠어요?",
    template: (item) => `I'll pay by ${item}.`,
    items: ["credit card", "debit card", "cash", "mobile pay", "contactless card",
      "card, split into two payments", "gift card", "credit card, tap to pay",
      "cash, and I'll take the change", "card, and I'd like a receipt",
      "mobile wallet", "card ending in 1234", "cash, exact amount",
      "credit, and could I get it in installments", "my company card",
      "a combination of cash and card", "card, no receipt needed",
      "cash, keep the change", "card, and please double the receipt",
      "whichever is easiest for you"],
    answersKo: ["신용카드로 결제할게요.", "체크카드로 결제할게요.", "현금으로 결제할게요.",
      "모바일 결제로 할게요.", "컨택리스 카드로 결제할게요.", "카드로 두 번 나눠서 결제할게요.",
      "기프트카드로 결제할게요.", "신용카드 탭으로 결제할게요.", "현금으로 내고 거스름돈 받을게요.",
      "카드로 하고 영수증도 주세요.", "모바일 지갑으로 결제할게요.", "1234로 끝나는 카드로 결제할게요.",
      "현금으로 정확히 낼게요.", "신용카드로 할부 가능할까요.", "회사 카드로 결제할게요.",
      "현금이랑 카드 섞어서 결제할게요.", "카드로 하고 영수증은 필요 없어요.", "현금으로 내고 거스름돈은 됐어요.",
      "카드로 하고 영수증 두 장 부탁드려요.", "편하신 방법으로 해주세요."],
  },
  {
    id: "bank_account",
    title: "은행 계좌 개설",
    npc: "Hi, what can I help you with today?",
    npcKo: "안녕하세요, 오늘 어떻게 도와드릴까요?",
    template: (item) => `I'd like to ${item}.`,
    items: ["open a checking account", "open a savings account", "apply for a debit card",
      "set up online banking", "close my old account", "update my address",
      "apply for a credit card", "increase my card limit", "get a new PIN",
      "set up automatic transfers", "check my account balance",
      "report a lost card", "transfer money to another account",
      "open a joint account", "get a bank statement", "set up direct deposit",
      "apply for a small loan", "convert my account to a foreign currency account",
      "get information about interest rates", "dispute a charge on my card"],
    answersKo: ["입출금 계좌를 개설하고 싶어요.", "저축 계좌를 개설하고 싶어요.", "체크카드를 신청하고 싶어요.",
      "온라인 뱅킹을 설정하고 싶어요.", "예전 계좌를 해지하고 싶어요.", "주소를 변경하고 싶어요.",
      "신용카드를 신청하고 싶어요.", "카드 한도를 늘리고 싶어요.", "새 비밀번호를 발급받고 싶어요.",
      "자동이체를 설정하고 싶어요.", "계좌 잔액을 확인하고 싶어요.", "분실 카드를 신고하고 싶어요.",
      "다른 계좌로 송금하고 싶어요.", "공동 계좌를 개설하고 싶어요.", "거래명세서를 받고 싶어요.",
      "급여 자동입금을 설정하고 싶어요.", "소액 대출을 신청하고 싶어요.", "외화 계좌로 전환하고 싶어요.",
      "금리 정보를 알고 싶어요.", "카드 이용내역에 이의를 제기하고 싶어요."],
  },
  {
    id: "currency_exchange",
    title: "환전하기",
    npc: "Welcome, what currency would you like to exchange today?",
    npcKo: "어서오세요, 오늘 어떤 통화로 환전해드릴까요?",
    template: (item) => `I'd like to exchange this for ${item}.`,
    items: ["US dollars", "euros", "Japanese yen", "British pounds", "Korean won",
      "Canadian dollars", "Australian dollars", "Chinese yuan", "Thai baht",
      "Vietnamese dong", "Singapore dollars", "Swiss francs", "Mexican pesos",
      "Indian rupees", "Hong Kong dollars", "New Zealand dollars",
      "Philippine pesos", "Malaysian ringgit", "Indonesian rupiah", "Taiwanese dollars"],
    answersKo: ["미국 달러로 환전하고 싶어요.", "유로로 환전하고 싶어요.", "일본 엔화로 환전하고 싶어요.",
      "영국 파운드로 환전하고 싶어요.", "한국 원화로 환전하고 싶어요.", "캐나다 달러로 환전하고 싶어요.",
      "호주 달러로 환전하고 싶어요.", "중국 위안화로 환전하고 싶어요.", "태국 바트로 환전하고 싶어요.",
      "베트남 동으로 환전하고 싶어요.", "싱가포르 달러로 환전하고 싶어요.", "스위스 프랑으로 환전하고 싶어요.",
      "멕시코 페소로 환전하고 싶어요.", "인도 루피로 환전하고 싶어요.", "홍콩 달러로 환전하고 싶어요.",
      "뉴질랜드 달러로 환전하고 싶어요.", "필리핀 페소로 환전하고 싶어요.", "말레이시아 링깃으로 환전하고 싶어요.",
      "인도네시아 루피아로 환전하고 싶어요.", "대만 달러로 환전하고 싶어요."],
  },
  {
    id: "withdraw_cash",
    title: "ATM/현금 인출",
    npc: "Is there anything I can help you with at the counter today?",
    npcKo: "오늘 창구에서 도와드릴 일이 있을까요?",
    template: (item) => `I'd like to withdraw ${item}, please.`,
    items: ["one hundred dollars", "fifty dollars", "two hundred dollars",
      "some cash for the week", "twenty dollars in small bills",
      "three hundred dollars", "a small amount, just in case",
      "cash for a taxi", "some local currency", "a round number, like a hundred",
      "enough for groceries", "cash for an emergency", "150 dollars",
      "the maximum daily amount", "a few small bills and some coins",
      "cash without a fee if possible", "500 in local currency",
      "a mix of bills and coins", "just enough to cover today's expenses",
      "seventy-five dollars"],
    answersKo: ["100달러 인출하고 싶어요.", "50달러 인출하고 싶어요.", "200달러 인출하고 싶어요.",
      "이번 주 쓸 현금을 인출하고 싶어요.", "소액권으로 20달러 인출하고 싶어요.", "300달러 인출하고 싶어요.",
      "만약을 위해 소액만 인출하고 싶어요.", "택시비로 쓸 현금을 인출하고 싶어요.", "현지 통화로 좀 인출하고 싶어요.",
      "딱 100달러 정도 인출하고 싶어요.", "장 볼 만큼 인출하고 싶어요.", "비상금으로 인출하고 싶어요.",
      "150달러 인출하고 싶어요.", "하루 최대 한도만큼 인출하고 싶어요.", "소액권이랑 동전 좀 섞어서 인출하고 싶어요.",
      "가능하면 수수료 없이 인출하고 싶어요.", "현지 통화로 500 인출하고 싶어요.", "지폐랑 동전 섞어서 인출하고 싶어요.",
      "오늘 쓸 만큼만 인출하고 싶어요.", "75달러 인출하고 싶어요."],
  },
  {
    id: "post_office",
    title: "우체국 이용하기",
    npc: "Hi, what can I help you send today?",
    npcKo: "안녕하세요, 오늘 뭘 보내시나요?",
    template: (item) => `I'd like to send ${item}.`,
    items: ["this package overseas", "a letter by express mail", "this box to Korea",
      "a postcard", "this parcel with tracking", "a document by registered mail",
      "this gift to my family", "a fragile item, so please handle with care",
      "this package by the cheapest method", "an envelope internationally",
      "this box, and I need it insured", "a package that needs to arrive by Friday",
      "this letter domestically", "a heavy parcel, so I need to weigh it first",
      "this box with extra padding", "a same-day delivery item",
      "this to a business address", "a return package",
      "this with signature required on delivery", "a bulk shipment"],
    answersKo: ["이 소포를 해외로 보내고 싶어요.", "이 편지를 특급우편으로 보내고 싶어요.",
      "이 상자를 한국으로 보내고 싶어요.", "엽서를 보내고 싶어요.", "이 소포를 추적 가능하게 보내고 싶어요.",
      "이 서류를 등기로 보내고 싶어요.", "이 선물을 가족에게 보내고 싶어요.", "깨지기 쉬운 물건이니 조심히 다뤄주세요.",
      "이 소포를 가장 저렴한 방법으로 보내고 싶어요.", "봉투를 해외로 보내고 싶어요.",
      "이 상자를 보험 들어서 보내고 싶어요.", "금요일까지 도착해야 하는 소포예요.",
      "이 편지를 국내로 보내고 싶어요.", "무거운 소포라 먼저 무게를 재야 해요.",
      "이 상자를 완충재 추가해서 보내고 싶어요.", "당일 배송으로 보내고 싶어요.",
      "이걸 사업장 주소로 보내고 싶어요.", "반품 소포를 보내고 싶어요.",
      "수령 시 서명이 필요한 걸로 보내고 싶어요.", "대량 발송을 하고 싶어요."],
  },
  {
    id: "pharmacy",
    title: "약국 이용하기",
    npc: "Hi, how can I help you today?",
    npcKo: "안녕하세요, 오늘 어떻게 도와드릴까요?",
    template: (item) => `I have ${item}. What would you recommend?`,
    items: ["a headache", "a sore throat", "a cough", "a stuffy nose", "a fever",
      "an upset stomach", "allergies", "a skin rash", "a toothache",
      "muscle pain", "insomnia", "a bad cold", "motion sickness",
      "a mild burn", "a cut that needs a bandage", "back pain",
      "eye irritation", "seasonal allergies", "a mosquito bite", "heartburn"],
    answersKo: ["두통이 있는데 뭐가 좋을까요?", "목이 아픈데 뭐가 좋을까요?", "기침이 나는데 뭐가 좋을까요?",
      "코가 막혔는데 뭐가 좋을까요?", "열이 나는데 뭐가 좋을까요?", "배탈이 났는데 뭐가 좋을까요?",
      "알레르기가 있는데 뭐가 좋을까요?", "피부 발진이 있는데 뭐가 좋을까요?", "치통이 있는데 뭐가 좋을까요?",
      "근육통이 있는데 뭐가 좋을까요?", "불면증이 있는데 뭐가 좋을까요?", "독감 기운이 있는데 뭐가 좋을까요?",
      "멀미가 나는데 뭐가 좋을까요?", "가벼운 화상을 입었는데 뭐가 좋을까요?", "밴드가 필요한 상처가 있는데 뭐가 좋을까요?",
      "허리가 아픈데 뭐가 좋을까요?", "눈이 따가운데 뭐가 좋을까요?", "계절성 알레르기가 있는데 뭐가 좋을까요?",
      "모기 물린 데가 있는데 뭐가 좋을까요?", "속쓰림이 있는데 뭐가 좋을까요?"],
  },
  {
    id: "doctor_visit",
    title: "병원 진료받기",
    npc: "What brings you in today? Tell me how you're feeling.",
    npcKo: "오늘 어떻게 오셨어요? 어디가 안 좋으신지 말씀해 주세요.",
    template: (item) => `I've had ${item} for a couple of days.`,
    items: ["a high fever", "a persistent cough", "a sore throat", "stomach pain",
      "a headache", "dizziness", "shortness of breath", "joint pain",
      "a skin rash", "back pain", "nausea", "chest pain",
      "trouble sleeping", "a swollen ankle", "ear pain", "blurry vision",
      "a stiff neck", "loss of appetite", "fatigue", "a persistent runny nose"],
    answersKo: ["이틀째 고열이 있어요.", "이틀째 기침이 계속돼요.", "이틀째 목이 아파요.",
      "이틀째 복통이 있어요.", "이틀째 두통이 있어요.", "이틀째 어지러워요.",
      "이틀째 숨이 차요.", "이틀째 관절이 아파요.", "이틀째 피부 발진이 있어요.",
      "이틀째 허리가 아파요.", "이틀째 메스꺼워요.", "이틀째 가슴이 아파요.",
      "이틀째 잠을 잘 못 자요.", "이틀째 발목이 부었어요.", "이틀째 귀가 아파요.",
      "이틀째 시야가 흐려요.", "이틀째 목이 뻣뻣해요.", "이틀째 입맛이 없어요.",
      "이틀째 피곤해요.", "이틀째 콧물이 계속 나요."],
  },
  {
    id: "dentist_appointment",
    title: "치과 진료받기",
    npc: "What seems to be the problem with your teeth today?",
    npcKo: "오늘 치아에 어떤 문제가 있으세요?",
    template: (item) => `I've been having ${item}.`,
    items: ["a toothache", "sensitivity to cold", "a chipped tooth", "bleeding gums",
      "pain when chewing", "a loose filling", "bad breath",
      "swelling around a tooth", "a cracked tooth", "jaw pain",
      "sensitivity to sweets", "gum pain", "a broken crown",
      "pain in my wisdom tooth", "sensitivity to hot drinks",
      "a cavity I think", "trouble flossing because of pain",
      "an ache that comes and goes", "pain after a filling", "trouble with my bite"],
    answersKo: ["치통이 있어요.", "찬 것에 민감해요.", "이가 깨졌어요.", "잇몸에서 피가 나요.",
      "씹을 때 아파요.", "충전물이 헐거워졌어요.", "입 냄새가 나요.", "이 주변이 부었어요.",
      "이가 금이 갔어요.", "턱이 아파요.", "단 음식에 민감해요.", "잇몸이 아파요.",
      "크라운이 깨졌어요.", "사랑니가 아파요.", "뜨거운 음료에 민감해요.", "충치가 있는 것 같아요.",
      "아파서 치실질이 힘들어요.", "통증이 왔다 갔다 해요.", "충전 치료 후에 아파요.", "교합에 문제가 있어요."],
  },
  {
    id: "gym_membership",
    title: "헬스장 등록하기",
    npc: "Hi! Are you interested in becoming a member here?",
    npcKo: "안녕하세요! 저희 헬스장 등록에 관심 있으세요?",
    template: (item) => `Yes, I'm interested in ${item}.`,
    items: ["a monthly membership", "a one-year membership", "a trial pass",
      "personal training sessions", "group fitness classes", "a family membership",
      "a membership with pool access", "a student discount plan",
      "a membership I can pause anytime", "a membership with locker access",
      "just the basic plan", "a membership with sauna access",
      "signing up for a free trial first", "a weekend-only membership",
      "a membership that includes yoga classes", "a couples membership",
      "the premium plan with all facilities", "a short-term membership for a month",
      "off-peak hours membership", "a membership with nutrition coaching"],
    answersKo: ["네, 월 회원권에 관심 있어요.", "네, 1년 회원권에 관심 있어요.", "네, 체험권에 관심 있어요.",
      "네, 개인 트레이닝에 관심 있어요.", "네, 그룹 운동 수업에 관심 있어요.", "네, 가족 회원권에 관심 있어요.",
      "네, 수영장 이용 가능한 회원권에 관심 있어요.", "네, 학생 할인 요금제에 관심 있어요.",
      "네, 언제든 정지 가능한 회원권에 관심 있어요.", "네, 사물함 이용 가능한 회원권에 관심 있어요.",
      "네, 그냥 기본 요금제에 관심 있어요.", "네, 사우나 이용 가능한 회원권에 관심 있어요.",
      "네, 먼저 무료 체험 신청에 관심 있어요.", "네, 주말 전용 회원권에 관심 있어요.",
      "네, 요가 수업 포함 회원권에 관심 있어요.", "네, 커플 회원권에 관심 있어요.",
      "네, 모든 시설 포함 프리미엄 요금제에 관심 있어요.", "네, 한 달짜리 단기 회원권에 관심 있어요.",
      "네, 오프피크 시간 회원권에 관심 있어요.", "네, 영양 코칭 포함 회원권에 관심 있어요."],
  },
  {
    id: "gym_class_schedule",
    title: "헬스장 수업 일정 확인",
    npc: "Are you looking for a specific class today?",
    npcKo: "오늘 찾으시는 특정 수업 있으세요?",
    template: (item) => `Yes, what time is ${item}?`,
    items: ["the yoga class", "the spin class", "the boxing class", "the pilates class",
      "the morning HIIT class", "the swimming lesson", "the zumba class",
      "the strength training class", "the evening yoga session",
      "the beginner's class", "the CrossFit class", "the dance cardio class",
      "the stretching class", "the weekend bootcamp", "the kickboxing class",
      "the barre class", "the meditation session", "the aqua aerobics class",
      "the martial arts class", "the core workout class"],
    answersKo: ["네, 요가 수업은 몇 시예요?", "네, 스피닝 수업은 몇 시예요?", "네, 복싱 수업은 몇 시예요?",
      "네, 필라테스 수업은 몇 시예요?", "네, 아침 HIIT 수업은 몇 시예요?", "네, 수영 강습은 몇 시예요?",
      "네, 줌바 수업은 몇 시예요?", "네, 근력 운동 수업은 몇 시예요?", "네, 저녁 요가 수업은 몇 시예요?",
      "네, 초급자 수업은 몇 시예요?", "네, 크로스핏 수업은 몇 시예요?", "네, 댄스 카디오 수업은 몇 시예요?",
      "네, 스트레칭 수업은 몇 시예요?", "네, 주말 부트캠프는 몇 시예요?", "네, 킥복싱 수업은 몇 시예요?",
      "네, 바레 수업은 몇 시예요?", "네, 명상 세션은 몇 시예요?", "네, 아쿠아 에어로빅 수업은 몇 시예요?",
      "네, 무술 수업은 몇 시예요?", "네, 코어 운동 수업은 몇 시예요?"],
  },
  {
    id: "library_borrow",
    title: "도서관 이용하기",
    npc: "Hi, can I help you find something today?",
    npcKo: "안녕하세요, 오늘 찾으시는 거 도와드릴까요?",
    template: (item) => `I'm looking for ${item}.`,
    items: ["a mystery novel", "a science fiction book", "a history book",
      "a children's book for my daughter", "a cookbook", "a biography",
      "a book on learning English", "a graphic novel", "a poetry collection",
      "a travel guide", "a self-help book", "a book club recommendation",
      "an audiobook", "a magazine", "a newspaper archive",
      "a textbook for my class", "a bestseller", "a book in large print",
      "a research journal", "a book to borrow for two weeks"],
    answersKo: ["추리소설을 찾고 있어요.", "SF 소설을 찾고 있어요.", "역사책을 찾고 있어요.",
      "딸을 위한 동화책을 찾고 있어요.", "요리책을 찾고 있어요.", "전기를 찾고 있어요.",
      "영어 학습서를 찾고 있어요.", "그래픽노블을 찾고 있어요.", "시집을 찾고 있어요.",
      "여행 가이드북을 찾고 있어요.", "자기계발서를 찾고 있어요.", "북클럽 추천 도서를 찾고 있어요.",
      "오디오북을 찾고 있어요.", "잡지를 찾고 있어요.", "신문 보관본을 찾고 있어요.",
      "수업용 교재를 찾고 있어요.", "베스트셀러를 찾고 있어요.", "큰 글씨 책을 찾고 있어요.",
      "학술지를 찾고 있어요.", "2주 동안 빌릴 책을 찾고 있어요."],
  },
  {
    id: "hairdresser",
    title: "미용실 이용하기",
    npc: "Hi! What would you like to do with your hair today?",
    npcKo: "안녕하세요! 오늘 머리 어떻게 해드릴까요?",
    template: (item) => `I'd like ${item}, please.`,
    items: ["a haircut", "a trim, just the ends", "a shorter style",
      "layers added", "my hair dyed brown", "highlights",
      "a blow dry", "a perm", "bangs", "a fade on the sides",
      "a completely new style", "just a wash and style", "my hair straightened",
      "curls for a special event", "a color touch-up",
      "a treatment for damaged hair", "a buzz cut", "a shoulder-length cut",
      "an undercut", "my hair styled for a wedding"],
    answersKo: ["커트해 주세요.", "끝만 살짝 다듬어 주세요.", "더 짧은 스타일로 해주세요.",
      "레이어를 넣어주세요.", "머리를 갈색으로 염색해 주세요.", "하이라이트 넣어주세요.",
      "드라이해 주세요.", "파마해 주세요.", "앞머리 만들어 주세요.", "옆머리 페이드컷 해주세요.",
      "완전히 새로운 스타일로 해주세요.", "그냥 샴푸랑 스타일링만 해주세요.", "매직 스트레이트 해주세요.",
      "특별한 날이니 컬 넣어주세요.", "염색 뿌리만 정리해 주세요.", "손상모 트리트먼트 해주세요.",
      "삭발해 주세요.", "어깨 길이로 잘라주세요.", "언더컷 해주세요.", "결혼식용으로 머리 세팅해 주세요."],
  },
  {
    id: "phone_reservation",
    title: "전화로 예약하기",
    npc: "Thank you for calling. How can I help you?",
    npcKo: "전화 주셔서 감사합니다. 어떻게 도와드릴까요?",
    template: (item) => `I'd like to make a reservation for ${item}.`,
    items: ["two people at 7pm", "four people tomorrow evening", "a table by the window",
      "this Saturday at noon", "six people for a birthday dinner",
      "next Friday at 8pm", "a quiet table for two", "a party of five",
      "this weekend, any time works", "a table outside if possible",
      "3 people at 6:30", "a large group of ten", "next Tuesday at lunch",
      "a table near the entrance", "this evening at 9", "a private room for a meeting",
      "two people, and one has a food allergy", "a table for a business dinner",
      "tomorrow at 1pm", "a family of four"],
    answersKo: ["2명, 저녁 7시로 예약하고 싶어요.", "4명, 내일 저녁으로 예약하고 싶어요.",
      "창가 테이블로 예약하고 싶어요.", "이번 주 토요일 정오로 예약하고 싶어요.",
      "생일 저녁식사로 6명 예약하고 싶어요.", "다음 주 금요일 저녁 8시로 예약하고 싶어요.",
      "조용한 2인석으로 예약하고 싶어요.", "5명 자리로 예약하고 싶어요.",
      "이번 주말, 시간은 아무 때나 괜찮아요.", "가능하면 야외 테이블로 예약하고 싶어요.",
      "6시 30분에 3명으로 예약하고 싶어요.", "10명 단체석으로 예약하고 싶어요.",
      "다음 주 화요일 점심으로 예약하고 싶어요.", "입구 근처 테이블로 예약하고 싶어요.",
      "오늘 저녁 9시로 예약하고 싶어요.", "회의용 개인실로 예약하고 싶어요.",
      "2명인데 한 명은 음식 알레르기가 있어요.", "비즈니스 저녁식사용 테이블로 예약하고 싶어요.",
      "내일 오후 1시로 예약하고 싶어요.", "4인 가족 자리로 예약하고 싶어요."],
  },
  {
    id: "tech_support",
    title: "기술 지원 요청하기",
    npc: "Tech support, how can I help you today?",
    npcKo: "기술지원팀입니다, 오늘 어떻게 도와드릴까요?",
    template: (item) => `${item} isn't working properly.`,
    items: ["My laptop", "My internet connection", "My phone screen", "My printer",
      "My email account", "My wifi router", "My smart TV", "My webcam",
      "My keyboard", "My mouse", "The app", "My password reset link",
      "My account login", "My headphones", "My tablet",
      "My charger", "The website", "My speaker",
      "My laptop battery", "My software update"],
    answersKo: ["제 노트북이 제대로 작동을 안 해요.", "제 인터넷 연결이 제대로 작동을 안 해요.",
      "제 휴대폰 화면이 제대로 작동을 안 해요.", "제 프린터가 제대로 작동을 안 해요.",
      "제 이메일 계정이 제대로 작동을 안 해요.", "제 와이파이 공유기가 제대로 작동을 안 해요.",
      "제 스마트TV가 제대로 작동을 안 해요.", "제 웹캠이 제대로 작동을 안 해요.",
      "제 키보드가 제대로 작동을 안 해요.", "제 마우스가 제대로 작동을 안 해요.",
      "그 앱이 제대로 작동을 안 해요.", "제 비밀번호 재설정 링크가 제대로 작동을 안 해요.",
      "제 계정 로그인이 제대로 작동을 안 해요.", "제 헤드폰이 제대로 작동을 안 해요.",
      "제 태블릿이 제대로 작동을 안 해요.", "제 충전기가 제대로 작동을 안 해요.",
      "그 웹사이트가 제대로 작동을 안 해요.", "제 스피커가 제대로 작동을 안 해요.",
      "제 노트북 배터리가 제대로 작동을 안 해요.", "제 소프트웨어 업데이트가 제대로 작동을 안 해요."],
  },
  {
    id: "product_complaint",
    title: "제품 불만 제기하기",
    npc: "I'm sorry to hear that. Can you tell me what happened?",
    npcKo: "그런 일이 있으셨다니 죄송합니다. 무슨 일이 있었는지 말씀해 주시겠어요?",
    template: (item) => `${item}.`,
    items: ["The product arrived broken", "It stopped working after two days",
      "It's completely different from the pictures online", "I was charged twice for the same order",
      "The delivery was three weeks late", "I never received my order",
      "The box was empty when it arrived", "The item was missing several parts",
      "Customer service hasn't responded to my emails", "The size doesn't match what I ordered",
      "The product smells strongly of chemicals", "It broke the first time I used it",
      "The color faded after one wash", "I received someone else's order",
      "The warranty wasn't honored", "The instructions were missing",
      "It made a strange noise right out of the box", "The packaging didn't protect it at all",
      "I was overcharged for shipping", "The refund never went through"],
    answersKo: ["제품이 파손된 채로 도착했어요.", "이틀 만에 작동을 멈췄어요.", "온라인 사진이랑 완전히 달라요.",
      "같은 주문에 두 번 결제됐어요.", "배송이 3주나 늦었어요.", "주문한 게 아예 안 왔어요.",
      "상자가 빈 채로 도착했어요.", "부품이 여러 개 빠져있었어요.", "고객센터가 이메일에 답이 없어요.",
      "주문한 사이즈랑 달라요.", "제품에서 화학약품 냄새가 심하게 나요.", "처음 썼을 때 바로 고장 났어요.",
      "한 번 세탁했더니 색이 바랬어요.", "다른 사람 주문을 받았어요.", "보증이 적용 안 됐어요.",
      "설명서가 빠져있었어요.", "박스 열자마자 이상한 소리가 났어요.", "포장이 전혀 보호가 안 됐어요.",
      "배송비가 과다 청구됐어요.", "환불이 아직도 처리가 안 됐어요."],
  },
  {
    id: "job_interview",
    title: "면접 답변 연습",
    npc: "So, tell me a little about yourself. What are your strengths?",
    npcKo: "본인에 대해 조금 말씀해 주시겠어요? 강점이 뭐라고 생각하세요?",
    template: (item) => `I'd say one of my strengths is that I'm ${item}.`,
    items: ["very organized", "a good communicator", "quick to learn new things",
      "detail-oriented", "good at solving problems", "a team player",
      "very reliable", "good under pressure", "creative",
      "adaptable to change", "a strong leader", "very patient",
      "good at managing my time", "a fast learner", "good at multitasking",
      "very motivated", "good at giving feedback", "confident in public speaking",
      "very analytical", "passionate about my work"],
    answersKo: ["제 강점 중 하나는 체계적이라는 거예요.", "제 강점 중 하나는 의사소통을 잘한다는 거예요.",
      "제 강점 중 하나는 새로운 걸 빨리 배운다는 거예요.", "제 강점 중 하나는 꼼꼼하다는 거예요.",
      "제 강점 중 하나는 문제해결을 잘한다는 거예요.", "제 강점 중 하나는 팀워크가 좋다는 거예요.",
      "제 강점 중 하나는 신뢰할 수 있다는 거예요.", "제 강점 중 하나는 압박 속에서도 잘한다는 거예요.",
      "제 강점 중 하나는 창의적이라는 거예요.", "제 강점 중 하나는 변화에 잘 적응한다는 거예요.",
      "제 강점 중 하나는 리더십이 강하다는 거예요.", "제 강점 중 하나는 인내심이 많다는 거예요.",
      "제 강점 중 하나는 시간관리를 잘한다는 거예요.", "제 강점 중 하나는 습득이 빠르다는 거예요.",
      "제 강점 중 하나는 멀티태스킹을 잘한다는 거예요.", "제 강점 중 하나는 동기부여가 강하다는 거예요.",
      "제 강점 중 하나는 피드백을 잘 준다는 거예요.", "제 강점 중 하나는 발표에 자신 있다는 거예요.",
      "제 강점 중 하나는 분석적이라는 거예요.", "제 강점 중 하나는 제 일에 열정적이라는 거예요."],
  },
  {
    id: "apartment_viewing",
    title: "집 보러 가기",
    npc: "Thanks for coming! What are you looking for in an apartment?",
    npcKo: "와주셔서 감사합니다! 어떤 집을 찾고 계세요?",
    template: (item) => `I'm mainly looking for a place with ${item}.`,
    items: ["good natural light", "a nearby subway station", "a quiet neighborhood",
      "a parking space", "a pet-friendly policy", "a gym in the building",
      "two bedrooms", "a balcony", "a modern kitchen",
      "a short commute to downtown", "a low deposit", "a washer and dryer included",
      "high-speed internet already set up", "a secure entrance",
      "a nearby grocery store", "a bathtub, not just a shower",
      "central heating", "storage space", "a rooftop terrace",
      "flexible lease terms"],
    answersKo: ["채광이 좋은 곳을 주로 찾고 있어요.", "지하철역 가까운 곳을 주로 찾고 있어요.",
      "조용한 동네를 주로 찾고 있어요.", "주차 공간 있는 곳을 주로 찾고 있어요.",
      "반려동물 가능한 곳을 주로 찾고 있어요.", "건물 내 헬스장 있는 곳을 주로 찾고 있어요.",
      "방 두 개인 곳을 주로 찾고 있어요.", "발코니 있는 곳을 주로 찾고 있어요.",
      "현대식 주방 있는 곳을 주로 찾고 있어요.", "시내까지 통근 짧은 곳을 주로 찾고 있어요.",
      "보증금 낮은 곳을 주로 찾고 있어요.", "세탁기 건조기 포함된 곳을 주로 찾고 있어요.",
      "고속 인터넷 이미 설치된 곳을 주로 찾고 있어요.", "보안 출입구 있는 곳을 주로 찾고 있어요.",
      "근처에 마트 있는 곳을 주로 찾고 있어요.", "샤워부스 말고 욕조 있는 곳을 주로 찾고 있어요.",
      "중앙난방 되는 곳을 주로 찾고 있어요.", "수납공간 넉넉한 곳을 주로 찾고 있어요.",
      "루프탑 테라스 있는 곳을 주로 찾고 있어요.", "계약 조건 유연한 곳을 주로 찾고 있어요."],
  },
  {
    id: "house_rules",
    title: "집/숙소 규칙 물어보기",
    npc: "Before you move in, let me go over a few things.",
    npcKo: "입주하시기 전에 몇 가지 짚고 넘어갈게요.",
    template: (item) => `Just to confirm, is ${item} allowed?`,
    items: ["having a pet", "smoking on the balcony", "having guests overnight",
      "playing music after 10pm", "subletting the room", "painting the walls",
      "hanging pictures on the walls", "using the shared laundry after midnight",
      "parking a second car", "having a small party occasionally",
      "keeping bikes in the hallway", "using the balcony for a small grill",
      "having packages delivered to the front desk", "changing the locks",
      "having a roommate move in later", "storing extra furniture in the garage",
      "using the rooftop after sunset", "having visitors during weekdays",
      "installing a washing machine", "putting up curtains of my own"],
    answersKo: ["확인차 여쭤보는데, 반려동물 키워도 되나요?", "확인차 여쭤보는데, 발코니에서 흡연해도 되나요?",
      "확인차 여쭤보는데, 손님이 자고 가도 되나요?", "확인차 여쭤보는데, 밤 10시 이후 음악 틀어도 되나요?",
      "확인차 여쭤보는데, 방을 재임대해도 되나요?", "확인차 여쭤보는데, 벽에 페인트칠해도 되나요?",
      "확인차 여쭤보는데, 벽에 액자 걸어도 되나요?", "확인차 여쭤보는데, 자정 넘어 공용 세탁기 써도 되나요?",
      "확인차 여쭤보는데, 차 한 대 더 주차해도 되나요?", "확인차 여쭤보는데, 가끔 작은 파티 열어도 되나요?",
      "확인차 여쭤보는데, 복도에 자전거 둬도 되나요?", "확인차 여쭤보는데, 발코니에서 간단히 그릴 써도 되나요?",
      "확인차 여쭤보는데, 택배를 프론트에서 받아도 되나요?", "확인차 여쭤보는데, 자물쇠를 바꿔도 되나요?",
      "확인차 여쭤보는데, 룸메이트가 나중에 들어와도 되나요?", "확인차 여쭤보는데, 여분 가구를 창고에 보관해도 되나요?",
      "확인차 여쭤보는데, 해질녘 이후 옥상 이용해도 되나요?", "확인차 여쭤보는데, 평일에 손님 받아도 되나요?",
      "확인차 여쭤보는데, 세탁기를 설치해도 되나요?", "확인차 여쭤보는데, 제 커튼을 달아도 되나요?"],
  },
  {
    id: "wifi_password",
    title: "와이파이 비밀번호 묻기",
    npc: "Let me know if you need anything to get settled in.",
    npcKo: "적응하는 데 필요한 게 있으면 말씀해 주세요.",
    template: (item) => `Actually, could you tell me ${item}?`,
    items: ["the wifi password", "the wifi network name", "if there's a guest network",
      "how to reset the router", "where the router is located",
      "if the wifi covers the whole apartment", "the internet provider's number",
      "if there's a data limit", "how fast the internet speed is",
      "if I need a separate password for the smart TV", "the backup wifi option",
      "how to connect my laptop", "if there's 5G wifi available",
      "the router's admin password", "if guests can use a separate network",
      "how to troubleshoot a weak signal", "if the wifi works on the balcony",
      "the technical support number", "if there's ethernet available too",
      "when the wifi bill is due"],
    answersKo: ["와이파이 비밀번호 좀 알려주시겠어요?", "와이파이 네트워크 이름 좀 알려주시겠어요?",
      "게스트 네트워크가 있는지 알려주시겠어요?", "공유기 재설정하는 방법 알려주시겠어요?",
      "공유기가 어디 있는지 알려주시겠어요?", "와이파이가 집 전체에 다 잡히는지 알려주시겠어요?",
      "인터넷 회사 전화번호 알려주시겠어요?", "데이터 제한이 있는지 알려주시겠어요?",
      "인터넷 속도가 얼마나 빠른지 알려주시겠어요?", "스마트TV용 비밀번호가 따로 필요한지 알려주시겠어요?",
      "백업 와이파이 옵션이 있는지 알려주시겠어요?", "노트북 연결하는 방법 알려주시겠어요?",
      "5G 와이파이가 되는지 알려주시겠어요?", "공유기 관리자 비밀번호 알려주시겠어요?",
      "손님용 별도 네트워크 쓸 수 있는지 알려주시겠어요?", "신호가 약할 때 해결하는 방법 알려주시겠어요?",
      "발코니에서도 와이파이가 되는지 알려주시겠어요?", "기술지원 전화번호 알려주시겠어요?",
      "유선 인터넷도 되는지 알려주시겠어요?", "와이파이 요금이 언제 나가는지 알려주시겠어요?"],
  },
  {
    id: "movie_recommend",
    title: "영화 추천 대화",
    npc: "Have you seen any good movies lately?",
    npcKo: "요즘 재밌게 본 영화 있으세요?",
    template: (item) => `I really enjoyed a ${item} recently.`,
    items: ["romantic comedy", "action movie", "documentary", "horror film",
      "animated movie", "mystery thriller", "science fiction film",
      "historical drama", "musical", "superhero movie",
      "war film", "coming-of-age story", "crime drama",
      "fantasy movie", "psychological thriller", "family movie",
      "indie film", "biographical film", "adventure movie", "comedy special"],
    answersKo: ["로맨틱 코미디를 정말 재밌게 봤어요.", "액션 영화를 정말 재밌게 봤어요.",
      "다큐멘터리를 정말 재밌게 봤어요.", "공포 영화를 정말 재밌게 봤어요.", "애니메이션 영화를 정말 재밌게 봤어요.",
      "미스터리 스릴러를 정말 재밌게 봤어요.", "SF 영화를 정말 재밌게 봤어요.", "역사 드라마를 정말 재밌게 봤어요.",
      "뮤지컬을 정말 재밌게 봤어요.", "슈퍼히어로 영화를 정말 재밌게 봤어요.", "전쟁 영화를 정말 재밌게 봤어요.",
      "성장 영화를 정말 재밌게 봤어요.", "범죄 드라마를 정말 재밌게 봤어요.", "판타지 영화를 정말 재밌게 봤어요.",
      "심리 스릴러를 정말 재밌게 봤어요.", "가족 영화를 정말 재밌게 봤어요.", "독립영화를 정말 재밌게 봤어요.",
      "전기 영화를 정말 재밌게 봤어요.", "모험 영화를 정말 재밌게 봤어요.", "코미디 스페셜을 정말 재밌게 봤어요."],
  },
  {
    id: "restaurant_recommend",
    title: "맛집 추천 대화",
    npc: "Do you know any good places to eat around here?",
    npcKo: "이 근처에 맛있는 식당 아시는 거 있으세요?",
    template: (item) => `Yeah, there's a great ${item} restaurant nearby.`,
    items: ["Italian", "Japanese", "Korean", "Mexican", "Thai",
      "French", "Indian", "Vietnamese", "Chinese", "Mediterranean",
      "seafood", "vegetarian", "steak", "barbecue", "sushi",
      "ramen", "tapas", "brunch", "fusion", "dessert"],
    answersKo: ["네, 근처에 괜찮은 이탈리안 식당이 있어요.", "네, 근처에 괜찮은 일식당이 있어요.",
      "네, 근처에 괜찮은 한식당이 있어요.", "네, 근처에 괜찮은 멕시칸 식당이 있어요.",
      "네, 근처에 괜찮은 태국 식당이 있어요.", "네, 근처에 괜찮은 프렌치 식당이 있어요.",
      "네, 근처에 괜찮은 인도 식당이 있어요.", "네, 근처에 괜찮은 베트남 식당이 있어요.",
      "네, 근처에 괜찮은 중식당이 있어요.", "네, 근처에 괜찮은 지중해식 식당이 있어요.",
      "네, 근처에 괜찮은 해산물 식당이 있어요.", "네, 근처에 괜찮은 채식 식당이 있어요.",
      "네, 근처에 괜찮은 스테이크 식당이 있어요.", "네, 근처에 괜찮은 바베큐 식당이 있어요.",
      "네, 근처에 괜찮은 스시집이 있어요.", "네, 근처에 괜찮은 라멘집이 있어요.",
      "네, 근처에 괜찮은 타파스 식당이 있어요.", "네, 근처에 괜찮은 브런치 식당이 있어요.",
      "네, 근처에 괜찮은 퓨전 식당이 있어요.", "네, 근처에 괜찮은 디저트 가게가 있어요."],
  },
  {
    id: "borrow_neighbor",
    title: "이웃에게 물건 빌리기",
    npc: "Oh hi! Did you need something?",
    npcKo: "아, 안녕하세요! 뭐 필요하신 거 있으세요?",
    template: (item) => `Sorry to bother you, but could I borrow ${item}?`,
    items: ["a ladder", "some sugar", "a phone charger", "an umbrella",
      "a screwdriver", "some eggs", "a first aid kit", "jumper cables",
      "a vacuum cleaner", "a step stool", "some flour", "a bike pump",
      "an extension cord", "a spare key", "a measuring cup",
      "a flashlight", "a toolbox", "some tape", "a fan for the summer",
      "a few chairs for a small gathering"],
    answersKo: ["번거롭게 해드려 죄송한데, 사다리 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 설탕 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 휴대폰 충전기 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 우산 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 드라이버 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 계란 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 구급상자 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 점프케이블 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 청소기 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 발판 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 밀가루 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 자전거 펌프 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 연장 코드 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 여분 열쇠 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 계량컵 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 손전등 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 공구함 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 테이프 좀 빌릴 수 있을까요?",
      "번거롭게 해드려 죄송한데, 여름용 선풍기 좀 빌릴 수 있을까요?", "번거롭게 해드려 죄송한데, 작은 모임용 의자 몇 개 빌릴 수 있을까요?"],
  },
  {
    id: "food_delivery",
    title: "배달 음식 주문하기",
    npc: "Thanks for calling! What would you like to order?",
    npcKo: "전화 주셔서 감사합니다! 뭘 주문하시겠어요?",
    template: (item) => `I'd like to order ${item}, please.`,
    items: ["a large pepperoni pizza", "two bowls of ramen", "a chicken curry with rice",
      "a family-size fried chicken combo", "sushi for two", "a vegetable stir-fry",
      "a bacon cheeseburger meal", "pad thai", "a burrito with extra guacamole",
      "three tacos and a soda", "a bibimbap bowl", "a seafood pasta",
      "a large salad with grilled chicken", "dumplings and fried rice",
      "a Hawaiian pizza with extra cheese", "a chicken sandwich meal",
      "pho with extra noodles", "a spicy tofu stew", "a club sandwich",
      "General Tso's chicken with rice"],
    answersKo: ["라지 페퍼로니 피자 주문할게요.", "라면 두 그릇 주문할게요.", "치킨 커리랑 밥 주문할게요.",
      "패밀리 사이즈 프라이드치킨 세트 주문할게요.", "2인분 스시 주문할게요.", "채소 볶음 주문할게요.",
      "베이컨 치즈버거 세트 주문할게요.", "팟타이 주문할게요.", "과카몰리 추가한 부리토 주문할게요.",
      "타코 세 개랑 콜라 주문할게요.", "비빔밥 한 그릇 주문할게요.", "해산물 파스타 주문할게요.",
      "닭가슴살 얹은 라지 샐러드 주문할게요.", "만두랑 볶음밥 주문할게요.", "치즈 추가한 하와이안 피자 주문할게요.",
      "치킨 샌드위치 세트 주문할게요.", "면 추가한 쌀국수 주문할게요.", "매운 두부찌개 주문할게요.",
      "클럽 샌드위치 주문할게요.", "밥이랑 같이 나오는 깐풍기 주문할게요."],
  },
];

function buildCurriculum() {
  // Interleave categories round-robin (round 0: item[0] of every category, round
  // 1: item[1] of every category, ...) instead of laying out one category's 20
  // items back to back. Otherwise a single category (20 items = 4 days) would
  // occupy 4 consecutive days with the same NPC line repeated 20 times in a row.
  const itemsPerCategory = CATEGORY_TEMPLATES[0].items.length;
  const scenarios = [];
  for (let round = 0; round < itemsPerCategory; round++) {
    CATEGORY_TEMPLATES.forEach((cat) => {
      const item = cat.items[round];
      scenarios.push({
        categoryId: cat.id,
        categoryTitle: cat.title,
        npc: cat.npc,
        npcKo: cat.npcKo,
        answer: cat.template(item),
        answerKo: cat.answersKo[round],
        keyword: item.replace(/^(a |an |the )/i, "").split(",")[0].trim(),
      });
    });
  }
  scenarios.forEach((s, i) => {
    s.day = Math.floor(i / 5) + 1;
    s.slot = (i % 5) + 1;
    s.id = `d${s.day}-${s.slot}`;
  });
  return scenarios;
}

const CURRICULUM = buildCurriculum();
const CURRICULUM_TOTAL_DAYS = Math.ceil(CURRICULUM.length / 5);
