// 1000-word flashcard deck: 50 topic categories x 20 words each.
// Priority order: travel (15 categories), dating/relationships (10 categories),
// then general daily life (25 categories) fills out the rest.
// Each category has one example-sentence template (en/ko) reused across its
// 20 words, so every word gets a natural example without hand-writing 1000
// unique sentences from scratch.

const FLASHCARD_CATEGORIES = [
  // ---------- TRAVEL (15 categories) ----------
  {
    title: "여행 - 공항/탑승",
    template: (en) => `Where is the ${en}?`,
    templateKo: (ko) => `${ko}이(가) 어디 있나요?`,
    words: [
      ["boarding gate", "탑승구"], ["baggage claim", "수하물 찾는 곳"], ["customs", "세관"],
      ["immigration", "출입국심사"], ["security checkpoint", "보안검색대"], ["duty-free shop", "면세점"],
      ["departure lounge", "출국 대기실"], ["boarding pass", "탑승권"], ["layover", "경유"],
      ["connecting flight", "연결편"], ["terminal", "터미널"], ["check-in counter", "체크인 카운터"],
      ["carry-on", "기내용 가방"], ["overhead bin", "짐칸"], ["flight attendant", "승무원"],
      ["runway", "활주로"], ["arrival", "도착"], ["departure", "출발"], ["delay", "지연"],
      ["boarding time", "탑승 시간"],
    ],
  },
  {
    title: "여행 - 호텔/숙박",
    template: (en) => `I'd like to ask about the ${en}.`,
    templateKo: (ko) => `${ko}에 대해 여쭤보고 싶어요.`,
    words: [
      ["check-in", "체크인"], ["check-out", "체크아웃"], ["reservation", "예약"], ["room key", "방 키"],
      ["housekeeping", "객실 청소"], ["concierge", "컨시어지"], ["lobby", "로비"], ["amenities", "편의시설"],
      ["minibar", "미니바"], ["room service", "룸서비스"], ["vacancy", "빈 방"], ["deposit", "보증금"],
      ["wake-up call", "모닝콜"], ["single room", "싱글룸"], ["suite", "스위트룸"], ["hostel", "호스텔"],
      ["bed and breakfast", "민박"], ["air conditioning", "에어컨"], ["Wi-Fi access", "와이파이 이용"],
      ["front desk", "프런트 데스크"],
    ],
  },
  {
    title: "여행 - 대중교통",
    template: (en) => `How do I get to the ${en}?`,
    templateKo: (ko) => `${ko}에 어떻게 가나요?`,
    words: [
      ["bus stop", "버스 정류장"], ["subway station", "지하철역"], ["train platform", "기차 승강장"],
      ["ticket office", "매표소"], ["taxi stand", "택시 승차장"], ["one-way ticket", "편도 티켓"],
      ["round-trip ticket", "왕복 티켓"], ["transfer", "환승"], ["timetable", "시간표"], ["fare", "요금"],
      ["rush hour", "러시아워"], ["express train", "급행열차"], ["local train", "완행열차"],
      ["ferry", "여객선"], ["cable car", "케이블카"], ["rental bike", "대여 자전거"],
      ["parking lot", "주차장"], ["toll", "통행료"], ["traffic jam", "교통 체증"], ["seat belt", "안전벨트"],
    ],
  },
  {
    title: "여행 - 관광/명소",
    template: (en) => `Let's visit the ${en}.`,
    templateKo: (ko) => `${ko}에 가봐요.`,
    words: [
      ["landmark", "랜드마크"], ["museum", "박물관"], ["art gallery", "미술관"], ["cathedral", "대성당"],
      ["temple", "사찰"], ["palace", "궁전"], ["monument", "기념비"], ["viewpoint", "전망대"],
      ["tour guide", "투어 가이드"], ["guided tour", "가이드 투어"], ["souvenir shop", "기념품 가게"],
      ["admission fee", "입장료"], ["opening hours", "운영 시간"], ["historical site", "유적지"],
      ["botanical garden", "식물원"], ["national park", "국립공원"], ["waterfall", "폭포"],
      ["skyline", "스카이라인"], ["local market", "현지 시장"], ["walking tour", "도보 투어"],
    ],
  },
  {
    title: "여행 - 준비물",
    template: (en) => `Don't forget to pack your ${en}.`,
    templateKo: (ko) => `${ko} 챙기는 거 잊지 마세요.`,
    words: [
      ["passport", "여권"], ["visa", "비자"], ["itinerary", "여행 일정"], ["travel insurance", "여행자 보험"],
      ["currency", "화폐"], ["adapter", "어댑터"], ["power bank", "보조배터리"], ["sunscreen", "선크림"],
      ["first aid kit", "구급상자"], ["packing list", "짐 목록"], ["suitcase", "캐리어"],
      ["backpack", "배낭"], ["travel pillow", "여행용 목베개"], ["guidebook", "가이드북"], ["map", "지도"],
      ["itemized receipt", "영수증"], ["boarding documents", "탑승 서류"], ["emergency contact", "비상 연락처"],
      ["travel adapter", "여행용 어댑터"], ["luggage tag", "수하물 태그"],
    ],
  },
  {
    title: "여행 - 현지 식당",
    template: (en) => `Can you recommend some ${en}?`,
    templateKo: (ko) => `${ko} 좀 추천해 주시겠어요?`,
    words: [
      ["local cuisine", "현지 음식"], ["street food", "길거리 음식"], ["specialty dish", "특별 요리"],
      ["vegetarian option", "채식 옵션"], ["food allergy", "음식 알레르기"], ["tap water", "수돗물"],
      ["bottled water", "생수"], ["tipping culture", "팁 문화"], ["food market", "식품 시장"],
      ["cooking class", "요리 수업"], ["spicy food", "매운 음식"], ["food truck", "푸드트럭"],
      ["dessert shop", "디저트 가게"], ["night market", "야시장"], ["seafood restaurant", "해산물 식당"],
      ["buffet", "뷔페"], ["fine dining", "파인 다이닝"], ["fast food", "패스트푸드"],
      ["home-cooked meal", "집밥"], ["food tour", "음식 투어"],
    ],
  },
  {
    title: "여행 - 응급/안전",
    template: (en) => `In case of emergency, look for the ${en}.`,
    templateKo: (ko) => `비상시엔 ${ko}을(를) 찾으세요.`,
    words: [
      ["emergency exit", "비상구"], ["fire extinguisher", "소화기"], ["first aid", "응급처치"],
      ["ambulance", "구급차"], ["police station", "경찰서"], ["embassy", "대사관"],
      ["lost and found", "분실물 센터"], ["travel advisory", "여행 경보"], ["pickpocket", "소매치기"],
      ["scam", "사기"], ["evacuation", "대피"], ["emergency number", "비상 연락처"], ["hospital", "병원"],
      ["pharmacy", "약국"], ["insurance claim", "보험 청구"], ["safe box", "금고"],
      ["curfew", "통행금지"], ["natural disaster", "자연재해"], ["quarantine", "격리"],
      ["travel warning", "여행 경보"],
    ],
  },
  {
    title: "여행 - 방향/길찾기",
    template: (en) => `Could you tell me ${en}?`,
    templateKo: (ko) => `${ko} 알려주시겠어요?`,
    words: [
      ["which way to go", "어느 쪽으로 가야 하는지"], ["how far it is", "얼마나 먼지"],
      ["the shortest route", "가장 빠른 길"], ["where I am", "제가 어디 있는지"],
      ["the nearest exit", "가장 가까운 출구"], ["the correct platform", "맞는 승강장"],
      ["a good landmark", "좋은 표지물"], ["the walking distance", "도보 거리"],
      ["the opposite direction", "반대 방향"], ["a detour", "우회로"], ["the crossroads", "교차로"],
      ["the roundabout", "로터리"], ["the dead end", "막다른 길"], ["the pedestrian crossing", "횡단보도"],
      ["the overpass", "육교"], ["the underpass", "지하도"], ["the intersection", "교차로"],
      ["the compass direction", "나침반 방향"], ["the GPS location", "GPS 위치"], ["the map app", "지도 앱"],
    ],
  },
  {
    title: "여행 - 환전/결제",
    template: (en) => `Where can I find ${en}?`,
    templateKo: (ko) => `${ko}을(를) 어디서 찾을 수 있나요?`,
    words: [
      ["currency exchange", "환전소"], ["ATM", "현금인출기"], ["exchange rate", "환율"],
      ["traveler's check", "여행자 수표"], ["service charge", "서비스 요금"], ["cash only", "현금만 가능"],
      ["credit card fee", "신용카드 수수료"], ["foreign transaction fee", "해외결제 수수료"],
      ["bargaining", "흥정"], ["receipt", "영수증"], ["small change", "잔돈"], ["tip jar", "팁 통"],
      ["budget travel", "저예산 여행"], ["price tag", "가격표"], ["discount coupon", "할인 쿠폰"],
      ["duty tax", "관세"], ["wire transfer", "송금"], ["prepaid card", "선불카드"],
      ["cash advance", "현금서비스"], ["refund", "환불"],
    ],
  },
  {
    title: "여행 - 날씨/자연",
    template: (en) => `The forecast says it will be ${en}.`,
    templateKo: (ko) => `일기예보에서 ${ko}라고 하네요.`,
    words: [
      ["humid", "습한"], ["dry season", "건기"], ["rainy season", "우기"], ["monsoon", "몬순"],
      ["heatwave", "폭염"], ["snowstorm", "눈보라"], ["sunrise", "일출"], ["sunset", "일몰"],
      ["altitude sickness", "고산병"], ["jet lag", "시차 적응"], ["time zone", "시간대"],
      ["tropical climate", "열대 기후"], ["coastal area", "해안 지역"], ["mountain range", "산맥"],
      ["desert", "사막"], ["island", "섬"], ["volcano", "화산"], ["hot spring", "온천"],
      ["coral reef", "산호초"], ["national border", "국경"],
    ],
  },
  {
    title: "여행 - 렌터카/운전",
    template: (en) => `I need to check the ${en} before driving.`,
    templateKo: (ko) => `운전 전에 ${ko}을(를) 확인해야 해요.`,
    words: [
      ["driver's license", "운전면허증"], ["international license", "국제운전면허증"],
      ["rental agreement", "대여 계약서"], ["insurance coverage", "보험 보장"], ["fuel gauge", "연료 게이지"],
      ["GPS navigation", "GPS 내비게이션"], ["speed limit", "제한 속도"], ["toll road", "유료 도로"],
      ["parking fine", "주차 위반 딱지"], ["road sign", "도로 표지판"], ["roundabout rule", "로터리 규칙"],
      ["gas station", "주유소"], ["flat tire", "펑크난 타이어"], ["spare tire", "스페어 타이어"],
      ["rearview mirror", "백미러"], ["seat adjustment", "좌석 조절"], ["one-way street", "일방통행 도로"],
      ["traffic light", "신호등"], ["pedestrian zone", "보행자 구역"], ["car trouble", "차량 고장"],
    ],
  },
  {
    title: "여행 - 쇼핑/기념품",
    template: (en) => `I'm looking for a nice ${en}.`,
    templateKo: (ko) => `괜찮은 ${ko}을(를) 찾고 있어요.`,
    words: [
      ["souvenir", "기념품"], ["handmade craft", "수공예품"], ["local specialty", "지역 특산품"],
      ["price negotiation", "가격 협상"], ["size chart", "사이즈표"], ["fitting room", "피팅룸"],
      ["duty-free item", "면세품"], ["tax refund", "세금 환급"], ["shopping district", "쇼핑 거리"],
      ["flea market", "벼룩시장"], ["antique shop", "골동품 가게"], ["postcard", "엽서"],
      ["magnet", "자석 기념품"], ["keychain", "열쇠고리"], ["craft market", "수공예 시장"],
      ["bargain price", "할인가"], ["quality check", "품질 확인"], ["packaging", "포장"],
      ["gift wrap", "선물 포장"], ["shopping bag", "쇼핑백"],
    ],
  },
  {
    title: "여행 - 사진/추억",
    template: (en) => `Let's take a photo of the ${en}.`,
    templateKo: (ko) => `${ko} 사진 찍어요.`,
    words: [
      ["scenic view", "경치"], ["photo spot", "포토 스팟"], ["panorama", "파노라마"],
      ["selfie stick", "셀카봉"], ["group photo", "단체 사진"], ["memory card", "메모리카드"],
      ["travel journal", "여행 일기"], ["photo album", "사진 앨범"], ["sunset view", "일몰 풍경"],
      ["night view", "야경"], ["drone shot", "드론 촬영"], ["candid photo", "자연스러운 사진"],
      ["filter", "필터"], ["camera lens", "카메라 렌즈"], ["tripod", "삼각대"], ["timelapse", "타임랩스"],
      ["backdrop", "배경"], ["landscape", "풍경"], ["cityscape", "도시 풍경"], ["keepsake", "기념품"],
    ],
  },
  {
    title: "여행 - 돌발 상황",
    template: (en) => `I had trouble with the ${en}.`,
    templateKo: (ko) => `${ko} 때문에 문제가 있었어요.`,
    words: [
      ["language barrier", "언어 장벽"], ["culture shock", "문화 충격"], ["time difference", "시차"],
      ["lost luggage", "분실된 짐"], ["flight cancellation", "항공편 취소"], ["overbooking", "초과 예약"],
      ["missed connection", "놓친 환승"], ["visa rejection", "비자 거절"], ["customs declaration", "세관 신고"],
      ["quarantine rule", "격리 규정"], ["travel restriction", "여행 제한"], ["roaming charge", "로밍 요금"],
      ["local SIM card", "현지 유심"], ["translation app", "번역 앱"], ["tour cancellation", "투어 취소"],
      ["weather delay", "기상 지연"], ["strike", "파업"], ["overtourism", "과잉 관광"],
      ["jet lag recovery", "시차 회복"], ["homesickness", "향수병"],
    ],
  },
  {
    title: "여행 - 감정/표현",
    template: (en) => `I felt so ${en} during the trip.`,
    templateKo: (ko) => `여행 중에 정말 ${ko} 느꼈어요.`,
    words: [
      ["adventurous", "모험심 있는"], ["overwhelmed", "벅찬"], ["relaxed", "편안한"],
      ["homesick", "향수병 나는"], ["excited", "신난"], ["exhausted", "지친"], ["amazed", "놀란"],
      ["grateful", "감사한"], ["curious", "호기심 있는"], ["nostalgic", "향수를 느끼는"],
      ["refreshed", "재충전된"], ["disoriented", "방향감각을 잃은"], ["inspired", "영감을 받은"],
      ["carefree", "근심 없는"], ["awestruck", "경외감을 느끼는"], ["culture-shocked", "문화충격을 받은"],
      ["content", "만족스러운"], ["peaceful", "평화로운"], ["thrilled", "짜릿한"], ["fulfilled", "충만한"],
    ],
  },

  // ---------- DATING & RELATIONSHIPS (10 categories) ----------
  {
    title: "연애 - 소개팅/데이트 신청",
    template: (en) => `Let's talk about the ${en}.`,
    templateKo: (ko) => `${ko}에 대해 얘기해봐요.`,
    words: [
      ["blind date", "소개팅"], ["first date", "첫 데이트"], ["dating app", "데이팅 앱"],
      ["matchmaking", "중매"], ["asking someone out", "데이트 신청하기"], ["love at first sight", "첫눈에 반함"],
      ["mutual friend", "공통 친구"], ["chemistry", "케미"], ["flirting", "추파"], ["small talk", "스몰토크"],
      ["exchanging numbers", "번호 교환"], ["follow-up text", "후속 문자"], ["coffee date", "커피 데이트"],
      ["dinner date", "저녁 데이트"], ["double date", "더블 데이트"], ["speed dating", "스피드 데이팅"],
      ["online dating", "온라인 데이팅"], ["dating profile", "데이팅 프로필"], ["first impression", "첫인상"],
      ["awkward silence", "어색한 침묵"],
    ],
  },
  {
    title: "연애 - 연애 초반",
    template: (en) => `We're still figuring out the ${en}.`,
    templateKo: (ko) => `저희는 아직 ${ko}을(를) 알아가는 중이에요.`,
    words: [
      ["crush", "짝사랑 상대"], ["butterflies", "설렘"], ["texting", "문자하기"], ["video call", "영상통화"],
      ["getting to know each other", "서로 알아가기"], ["common interests", "공통 관심사"],
      ["compatibility", "궁합"], ["spark", "스파크"], ["romantic tension", "로맨틱한 긴장감"],
      ["exclusivity", "독점적인 관계"], ["defining the relationship", "관계를 정의하기"],
      ["taking it slow", "천천히 진행하기"], ["red flag", "위험 신호"], ["green flag", "좋은 신호"],
      ["honeymoon phase", "허니문 기간"], ["meeting the friends", "친구들에게 소개하기"],
      ["hanging out", "함께 놀기"], ["casual dating", "가벼운 연애"], ["serious relationship", "진지한 관계"],
      ["official couple", "공식 커플"],
    ],
  },
  {
    title: "연애 - 애정 표현",
    template: (en) => `That's such a ${en} thing to say.`,
    templateKo: (ko) => `정말 ${ko} 말이네요.`,
    words: [
      ["sweet", "달콤한"], ["affectionate", "다정한"], ["tender", "다정한"], ["heartfelt", "진심 어린"],
      ["romantic", "로맨틱한"], ["loving", "사랑스러운"], ["warm", "따뜻한"], ["caring", "배려하는"],
      ["thoughtful", "사려 깊은"], ["gentle", "부드러운"], ["adoring", "흠모하는"], ["devoted", "헌신적인"],
      ["passionate", "열정적인"], ["cherished", "소중한"], ["endearing", "사랑스러운"],
      ["comforting", "위로가 되는"], ["genuine", "진실된"], ["intimate", "친밀한"],
      ["touching", "감동적인"], ["heartwarming", "마음이 따뜻해지는"],
    ],
  },
  {
    title: "연애 - 데이트 코스",
    template: (en) => `How about a ${en} this weekend?`,
    templateKo: (ko) => `이번 주말에 ${ko} 어때요?`,
    words: [
      ["movie night", "영화 보는 밤"], ["picnic", "소풍"], ["romantic dinner", "로맨틱한 저녁식사"],
      ["beach walk", "해변 산책"], ["amusement park visit", "놀이공원 방문"], ["wine tasting", "와인 시음"],
      ["cooking together", "함께 요리하기"], ["road trip", "드라이브 여행"], ["stargazing", "별 보기"],
      ["concert", "콘서트"], ["museum visit", "박물관 관람"], ["hike", "등산"], ["karaoke night", "노래방 가는 밤"],
      ["board game night", "보드게임 밤"], ["brunch date", "브런치 데이트"], ["sunset watching", "일몰 감상"],
      ["ice skating", "아이스 스케이팅"], ["art class", "미술 수업"], ["festival", "축제"],
      ["weekend getaway", "주말 여행"],
    ],
  },
  {
    title: "연애 - 감정/걱정",
    template: (en) => `I've been dealing with some ${en} lately.`,
    templateKo: (ko) => `요즘 ${ko} 때문에 힘들어요.`,
    words: [
      ["jealousy", "질투"], ["insecurity", "불안감"], ["trust issues", "신뢰 문제"],
      ["miscommunication", "소통 오류"], ["misunderstanding", "오해"], ["overthinking", "과도한 걱정"],
      ["anxiety", "불안"], ["vulnerability", "취약함"], ["mixed signals", "애매한 신호"],
      ["ghosting", "잠수 이별"], ["breadcrumbing", "희망고문"], ["commitment issues", "헌신에 대한 두려움"],
      ["fear of rejection", "거절에 대한 두려움"], ["longing", "그리움"], ["loneliness", "외로움"],
      ["heartache", "마음의 아픔"], ["doubt", "의심"], ["neediness", "집착"],
      ["emotional distance", "감정적 거리감"], ["overdependence", "과도한 의존"],
    ],
  },
  {
    title: "연애 - 갈등/화해",
    template: (en) => `We need to work on our ${en}.`,
    templateKo: (ko) => `우리 ${ko}을(를) 좀 더 노력해야 해요.`,
    words: [
      ["communication", "소통"], ["honesty", "솔직함"], ["compromise", "타협"], ["forgiveness", "용서"],
      ["apology", "사과"], ["active listening", "경청"], ["empathy", "공감"], ["patience", "인내심"],
      ["understanding", "이해"], ["respect", "존중"], ["boundaries", "선긋기"], ["common ground", "공통점"],
      ["taking responsibility", "책임지기"], ["conflict resolution", "갈등 해결"], ["cooling-off period", "냉각기"],
      ["silent treatment", "무언의 냉전"], ["making up", "화해하기"], ["trust rebuilding", "신뢰 회복"],
      ["emotional maturity", "정서적 성숙함"], ["vulnerability", "속마음을 여는 것"],
    ],
  },
  {
    title: "연애 - 헤어짐/이별",
    template: (en) => `It's hard to talk about the ${en}.`,
    templateKo: (ko) => `${ko}에 대해 얘기하기 힘들어요.`,
    words: [
      ["breakup", "이별"], ["heartbreak", "실연"], ["ex-girlfriend", "전 여자친구"],
      ["ex-boyfriend", "전 남자친구"], ["closure", "마무리"], ["moving on", "새출발하기"],
      ["mutual decision", "합의된 결정"], ["long-distance relationship", "장거리 연애"], ["cheating", "바람피우기"],
      ["betrayal", "배신"], ["broken heart", "상심"], ["getting over someone", "누군가를 잊는 것"],
      ["rebound relationship", "공백기 없는 새 연애"], ["no-contact rule", "연락 안 하기 규칙"],
      ["unrequited love", "짝사랑"], ["second chance", "재결합 기회"], ["reconciliation", "재결합"],
      ["divorce", "이혼"], ["separation", "별거"], ["letting go", "놓아주기"],
    ],
  },
  {
    title: "연애 - 청혼/결혼",
    template: (en) => `We're planning the ${en}.`,
    templateKo: (ko) => `저희 ${ko}을(를) 준비하고 있어요.`,
    words: [
      ["proposal", "청혼"], ["engagement ring", "약혼 반지"], ["fiancé", "약혼자(남)"],
      ["fiancée", "약혼녀"], ["wedding", "결혼식"], ["honeymoon", "신혼여행"], ["in-laws", "시댁·처가"],
      ["wedding vows", "결혼 서약"], ["bridesmaid", "신부 들러리"], ["groomsman", "신랑 들러리"],
      ["wedding anniversary", "결혼기념일"], ["newlyweds", "신혼부부"], ["prenup", "혼전계약서"],
      ["wedding reception", "결혼 피로연"], ["best man", "신랑 들러리 대표"], ["wedding ring", "결혼반지"],
      ["elopement", "사랑의 도피 결혼"], ["married life", "결혼 생활"], ["soulmate", "천생연분"],
      ["wedding venue", "결혼식장"],
    ],
  },
  {
    title: "연애 - 온라인 데이팅",
    template: (en) => `I'm not used to the ${en} yet.`,
    templateKo: (ko) => `아직 ${ko}이(가) 익숙하지 않아요.`,
    words: [
      ["swiping right", "오른쪽으로 스와이프하기"], ["match", "매칭"], ["profile picture", "프로필 사진"],
      ["bio", "자기소개"], ["catfishing", "가짜 프로필 사기"], ["being ghosted", "잠수 당하기"],
      ["super like", "슈퍼 라이크"], ["unmatching", "매칭 취소하기"], ["video chat", "영상 채팅"],
      ["in-person meeting", "실제 만남"], ["online persona", "온라인상의 이미지"], ["dating scam", "데이팅 사기"],
      ["verified profile", "인증된 프로필"], ["matching algorithm", "매칭 알고리즘"],
      ["icebreaker question", "아이스브레이킹 질문"], ["dating burnout", "데이팅 번아웃"],
      ["app notification", "앱 알림"], ["chat history", "채팅 기록"], ["blocking someone", "누군가를 차단하기"],
      ["reporting a user", "사용자를 신고하기"],
    ],
  },
  {
    title: "연애 - 성격/이상형",
    template: (en) => `I really like that you're so ${en}.`,
    templateKo: (ko) => `당신이 정말 ${ko} 게 좋아요.`,
    words: [
      ["funny", "재미있는"], ["caring", "배려심 있는"], ["ambitious", "야망 있는"], ["easygoing", "느긋한"],
      ["romantic", "로맨틱한"], ["loyal", "의리 있는"], ["supportive", "지지해주는"],
      ["independent", "독립적인"], ["family-oriented", "가정적인"], ["adventurous", "모험을 좋아하는"],
      ["down-to-earth", "현실적인"], ["confident", "자신감 있는"], ["sincere", "진실된"],
      ["playful", "장난기 있는"], ["mature", "성숙한"], ["considerate", "사려 깊은"],
      ["passionate", "열정적인"], ["reliable", "믿음직한"], ["affectionate", "다정한"],
      ["patient", "인내심 있는"],
    ],
  },

  // ---------- DAILY LIFE (25 categories) ----------
  {
    title: "일상 - 아침 루틴",
    template: (en) => `Every morning, I ${en}.`,
    templateKo: (ko) => `매일 아침 저는 ${ko}.`,
    words: [
      ["wake up", "일어나요"], ["brush my teeth", "양치해요"], ["take a shower", "샤워해요"],
      ["get dressed", "옷을 입어요"], ["make breakfast", "아침을 만들어요"], ["check my phone", "휴대폰을 확인해요"],
      ["comb my hair", "머리를 빗어요"], ["pack my bag", "가방을 싸요"], ["leave the house", "집을 나서요"],
      ["hit snooze", "알람을 미뤄요"], ["stretch", "스트레칭해요"], ["skip breakfast", "아침을 걸러요"],
      ["apply makeup", "화장해요"], ["shave", "면도해요"], ["set an alarm", "알람을 맞춰요"],
      ["feed the pet", "반려동물에게 먹이를 줘요"], ["water the plants", "식물에 물을 줘요"],
      ["read the news", "뉴스를 읽어요"], ["commute", "통근해요"], ["grab a coffee", "커피를 사요"],
    ],
  },
  {
    title: "일상 - 집안일",
    template: (en) => `I need to ${en} today.`,
    templateKo: (ko) => `오늘 ${ko} 해야 해요.`,
    words: [
      ["do the laundry", "빨래"], ["wash the dishes", "설거지"], ["vacuum", "청소기 돌리기"],
      ["mop the floor", "바닥 닦기"], ["take out the trash", "쓰레기 버리기"], ["dust", "먼지 털기"],
      ["make the bed", "침대 정리"], ["iron clothes", "다림질"], ["organize the closet", "옷장 정리"],
      ["clean the bathroom", "화장실 청소"], ["fold laundry", "빨래 개기"], ["sweep the floor", "바닥 쓸기"],
      ["water the plants", "식물에 물 주기"], ["tidy up", "정리"], ["do the groceries", "장보기"],
      ["cook dinner", "저녁 요리"], ["wash the windows", "창문 닦기"], ["declutter", "물건 정리"],
      ["change the bedsheets", "침대 시트 갈기"], ["unclog the drain", "배수구 뚫기"],
    ],
  },
  {
    title: "일상 - 주방/요리",
    template: (en) => `Could you pass me the ${en}?`,
    templateKo: (ko) => `${ko} 좀 건네주시겠어요?`,
    words: [
      ["stove", "가스레인지"], ["oven", "오븐"], ["microwave", "전자레인지"], ["refrigerator", "냉장고"],
      ["cutting board", "도마"], ["frying pan", "프라이팬"], ["ladle", "국자"], ["whisk", "거품기"],
      ["measuring cup", "계량컵"], ["recipe", "레시피"], ["pot", "냄비"], ["knife", "칼"],
      ["spatula", "뒤집개"], ["colander", "체"], ["mixing bowl", "믹싱볼"], ["can opener", "캔따개"],
      ["baking tray", "베이킹 팬"], ["kettle", "주전자"], ["blender", "믹서기"], ["rice cooker", "밥솥"],
    ],
  },
  {
    title: "일상 - 욕실/위생",
    template: (en) => `I ran out of ${en}.`,
    templateKo: (ko) => `${ko}이(가) 다 떨어졌어요.`,
    words: [
      ["toothpaste", "치약"], ["shampoo", "샴푸"], ["conditioner", "린스"], ["soap", "비누"],
      ["a towel", "수건"], ["razors", "면도기"], ["floss", "치실"], ["mouthwash", "구강청결제"],
      ["deodorant", "데오드란트"], ["lotion", "로션"], ["toilet paper", "화장지"],
      ["cotton swabs", "면봉"], ["nail clippers", "손톱깎이"], ["sunscreen", "자외선 차단제"],
      ["hand sanitizer", "손 소독제"], ["hair gel", "헤어젤"], ["body wash", "바디워시"],
      ["makeup remover", "클렌징 제품"], ["shaving cream", "쉐이빙 크림"], ["tissues", "티슈"],
    ],
  },
  {
    title: "일상 - 침실/가구",
    template: (en) => `We just bought a new ${en}.`,
    templateKo: (ko) => `저희 새 ${ko}을(를) 샀어요.`,
    words: [
      ["mattress", "매트리스"], ["pillow", "베개"], ["blanket", "이불"], ["closet", "옷장"],
      ["nightstand", "협탁"], ["alarm clock", "알람 시계"], ["curtains", "커튼"], ["dresser", "서랍장"],
      ["bookshelf", "책장"], ["desk", "책상"], ["chair", "의자"], ["lamp", "램프"], ["rug", "러그"],
      ["hanger", "옷걸이"], ["drawer", "서랍"], ["wardrobe", "옷장"], ["headboard", "침대 헤드보드"],
      ["bunk bed", "이층침대"], ["bedside table", "침대 옆 탁자"], ["comforter", "이불"],
    ],
  },
  {
    title: "일상 - 직장/업무",
    template: (en) => `I have a lot going on with the ${en}.`,
    templateKo: (ko) => `${ko} 때문에 요즘 바빠요.`,
    words: [
      ["deadline", "마감일"], ["meeting", "회의"], ["colleague", "동료"], ["boss", "상사"],
      ["promotion", "승진"], ["resignation", "사직"], ["salary", "월급"], ["overtime", "야근"],
      ["business trip", "출장"], ["presentation", "발표"], ["report", "보고서"], ["email", "이메일"],
      ["conference call", "전화 회의"], ["project", "프로젝트"], ["teamwork", "팀워크"],
      ["workload", "업무량"], ["performance review", "인사 평가"], ["job interview", "면접"],
      ["resume", "이력서"], ["work-life balance", "워라밸"],
    ],
  },
  {
    title: "일상 - 학교/교육",
    template: (en) => `I'm stressed about the ${en}.`,
    templateKo: (ko) => `${ko} 때문에 스트레스 받아요.`,
    words: [
      ["classroom", "교실"], ["homework", "숙제"], ["exam", "시험"], ["grade", "성적"],
      ["tuition", "등록금"], ["scholarship", "장학금"], ["lecture", "강의"], ["professor", "교수"],
      ["assignment", "과제"], ["semester", "학기"], ["graduation", "졸업"], ["major", "전공"],
      ["textbook", "교과서"], ["curriculum", "교육과정"], ["group project", "조별 과제"],
      ["attendance", "출석"], ["dormitory", "기숙사"], ["tutor", "과외 선생님"],
      ["syllabus", "강의계획서"], ["plagiarism", "표절"],
    ],
  },
  {
    title: "일상 - 건강/신체",
    template: (en) => `The doctor asked about my ${en}.`,
    templateKo: (ko) => `의사 선생님이 제 ${ko}에 대해 물어봤어요.`,
    words: [
      ["symptoms", "증상"], ["diagnosis", "진단"], ["prescription", "처방전"], ["checkup", "건강검진"],
      ["vaccine", "백신"], ["immune system", "면역 체계"], ["blood pressure", "혈압"],
      ["allergy", "알레르기"], ["chronic illness", "만성 질환"], ["recovery", "회복"], ["surgery", "수술"],
      ["physical therapy", "물리치료"], ["nutrition", "영양"], ["exercise routine", "운동 루틴"],
      ["mental health", "정신 건강"], ["stress", "스트레스"], ["sleep schedule", "수면 패턴"],
      ["dehydration", "탈수"], ["metabolism", "신진대사"], ["wellness", "웰빙"],
    ],
  },
  {
    title: "일상 - 감정 표현",
    template: (en) => `Honestly, I've been feeling pretty ${en} lately.`,
    templateKo: (ko) => `솔직히 요즘 좀 ${ko} 느꼈어요.`,
    words: [
      ["happy", "행복하다고"], ["sad", "슬프다고"], ["angry", "화난다고"], ["anxious", "불안하다고"],
      ["relieved", "안심했다고"], ["frustrated", "답답하다고"], ["confused", "혼란스럽다고"],
      ["proud", "자랑스럽다고"], ["embarrassed", "당황스럽다고"], ["disappointed", "실망했다고"],
      ["hopeful", "희망적이라고"], ["bored", "지루하다고"], ["lonely", "외롭다고"],
      ["motivated", "의욕적이라고"], ["overwhelmed", "벅차다고"], ["content", "만족스럽다고"],
      ["nervous", "긴장된다고"], ["grateful", "감사하다고"], ["jealous", "질투 난다고"],
      ["guilty", "죄책감이 든다고"],
    ],
  },
  {
    title: "일상 - 성격",
    template: (en) => `People say I'm pretty ${en}.`,
    templateKo: (ko) => `사람들이 저더러 ${ko} 편이래요.`,
    words: [
      ["outgoing", "외향적인"], ["introverted", "내향적인"], ["stubborn", "고집 센"],
      ["generous", "너그러운"], ["honest", "정직한"], ["lazy", "게으른"], ["hardworking", "부지런한"],
      ["humble", "겸손한"], ["arrogant", "거만한"], ["patient", "인내심 있는"], ["impulsive", "충동적인"],
      ["cautious", "신중한"], ["optimistic", "낙관적인"], ["pessimistic", "비관적인"],
      ["curious", "호기심 많은"], ["sensitive", "예민한"], ["confident", "자신감 있는"],
      ["shy", "수줍은"], ["funny", "재미있는"], ["serious", "진지한"],
    ],
  },
  {
    title: "일상 - 날씨/계절",
    template: (en) => `I really love ${en}.`,
    templateKo: (ko) => `저는 ${ko}을(를) 정말 좋아해요.`,
    words: [
      ["spring", "봄"], ["summer", "여름"], ["fall", "가을"], ["winter", "겨울"],
      ["warm weather", "따뜻한 날씨"], ["humid days", "습한 날들"], ["drizzly mornings", "이슬비 내리는 아침"],
      ["thunderstorms", "뇌우"], ["heat waves", "폭염"], ["cold fronts", "한파"],
      ["sunny days", "맑은 날"], ["overcast skies", "흐린 하늘"], ["gentle breezes", "산들바람"],
      ["frosty mornings", "서리 낀 아침"], ["blizzards", "눈보라"], ["droughts", "가뭄"],
      ["monsoon season", "장마철"], ["mild climates", "온화한 기후"], ["clear skies", "맑은 하늘"],
      ["foggy days", "안개 낀 날"],
    ],
  },
  {
    title: "일상 - 교통수단",
    template: (en) => `I usually get around by ${en}.`,
    templateKo: (ko) => `저는 보통 ${ko}(으)로 이동해요.`,
    words: [
      ["bicycle", "자전거"], ["motorcycle", "오토바이"], ["scooter", "스쿠터"], ["subway", "지하철"],
      ["bus", "버스"], ["taxi", "택시"], ["train", "기차"], ["airplane", "비행기"], ["ferry", "여객선"],
      ["car", "자동차"], ["truck", "트럭"], ["van", "밴"], ["tram", "트램"], ["cable car", "케이블카"],
      ["skateboard", "스케이트보드"], ["carpool", "카풀"], ["rideshare", "차량 공유"],
      ["public transit", "대중교통"], ["private car", "자가용"], ["electric car", "전기차"],
    ],
  },
  {
    title: "일상 - 쇼핑 일반",
    template: (en) => `Could you help me with the ${en}?`,
    templateKo: (ko) => `${ko} 좀 도와주시겠어요?`,
    words: [
      ["cashier", "계산원"], ["receipt", "영수증"], ["discount", "할인"], ["sale", "세일"],
      ["price tag", "가격표"], ["shopping cart", "쇼핑카트"], ["checkout line", "계산대 줄"],
      ["membership card", "멤버십 카드"], ["warranty", "보증서"], ["exchange policy", "교환 정책"],
      ["online order", "온라인 주문"], ["delivery", "배송"], ["return policy", "반품 정책"],
      ["customer service", "고객 서비스"], ["bargain", "싸게 사는 물건"], ["brand", "브랜드"],
      ["quality", "품질"], ["size", "사이즈"], ["fitting room", "피팅룸"], ["stock", "재고"],
    ],
  },
  {
    title: "일상 - 은행/금융",
    template: (en) => `I'm trying to manage my ${en} better.`,
    templateKo: (ko) => `${ko}을(를) 더 잘 관리하려고 해요.`,
    words: [
      ["budget", "예산"], ["savings", "저축"], ["investment", "투자"], ["interest rate", "금리"],
      ["loan", "대출"], ["mortgage", "주택담보대출"], ["credit score", "신용 점수"], ["debt", "빚"],
      ["income", "소득"], ["expenses", "지출"], ["taxes", "세금"], ["insurance", "보험"],
      ["pension", "연금"], ["stock market", "주식 시장"], ["cryptocurrency", "암호화폐"],
      ["financial goals", "재정 목표"], ["emergency fund", "비상금"], ["retirement", "은퇴"],
      ["bills", "청구서"], ["paycheck", "급여"],
    ],
  },
  {
    title: "일상 - 기술/전자기기",
    template: (en) => `My ${en} isn't working right.`,
    templateKo: (ko) => `제 ${ko}이(가) 제대로 안 돼요.`,
    words: [
      ["smartphone", "스마트폰"], ["laptop", "노트북"], ["charger", "충전기"], ["battery", "배터리"],
      ["software update", "소프트웨어 업데이트"], ["wifi", "와이파이"], ["bluetooth", "블루투스"],
      ["app", "앱"], ["notification", "알림"], ["screen", "화면"], ["password", "비밀번호"],
      ["cloud storage", "클라우드 저장소"], ["virus", "바이러스"], ["social media", "소셜미디어"],
      ["streaming service", "스트리밍 서비스"], ["download", "다운로드"], ["upload", "업로드"],
      ["backup", "백업"], ["firmware", "펌웨어"], ["webcam", "웹캠"],
    ],
  },
  {
    title: "일상 - 가족/관계",
    template: (en) => `I'm close with my ${en}.`,
    templateKo: (ko) => `저는 ${ko}과(와) 가까워요.`,
    words: [
      ["parents", "부모님"], ["siblings", "형제자매"], ["grandparents", "조부모님"], ["cousins", "사촌들"],
      ["nephew", "조카(남)"], ["niece", "조카(여)"], ["in-laws", "시댁·처가"], ["stepfather", "새아버지"],
      ["stepmother", "새어머니"], ["twin", "쌍둥이"], ["extended family", "대가족"], ["guardian", "보호자"],
      ["ancestors", "조상"], ["descendants", "후손"], ["relatives", "친척"], ["spouse", "배우자"],
      ["single parent", "한부모"], ["adoptive family", "입양 가족"], ["blended family", "재혼 가정"],
      ["only child", "외동"],
    ],
  },
  {
    title: "일상 - 취미/여가",
    template: (en) => `I've gotten really into ${en} lately.`,
    templateKo: (ko) => `요즘 ${ko}에 푹 빠졌어요.`,
    words: [
      ["painting", "그림 그리기"], ["gardening", "원예"], ["knitting", "뜨개질"],
      ["photography", "사진 촬영"], ["reading", "독서"], ["gaming", "게임하기"],
      ["birdwatching", "탐조"], ["woodworking", "목공"], ["pottery", "도예"], ["calligraphy", "캘리그라피"],
      ["collecting", "수집"], ["hiking", "등산"], ["fishing", "낚시"], ["camping", "캠핑"],
      ["yoga", "요가"], ["dancing", "춤"], ["singing", "노래하기"], ["cooking", "요리"],
      ["journaling", "일기 쓰기"], ["meditation", "명상"],
    ],
  },
  {
    title: "일상 - 스포츠",
    template: (en) => `Do you want to play ${en} this weekend?`,
    templateKo: (ko) => `이번 주말에 ${ko} 하실래요?`,
    words: [
      ["soccer", "축구"], ["basketball", "농구"], ["baseball", "야구"], ["tennis", "테니스"],
      ["swimming", "수영"], ["running", "달리기"], ["cycling", "자전거 타기"], ["golf", "골프"],
      ["volleyball", "배구"], ["boxing", "복싱"], ["wrestling", "레슬링"], ["skiing", "스키"],
      ["snowboarding", "스노보드"], ["surfing", "서핑"], ["badminton", "배드민턴"],
      ["table tennis", "탁구"], ["martial arts", "무술"], ["gymnastics", "체조"],
      ["a marathon", "마라톤"], ["a team sport", "단체 스포츠"],
    ],
  },
  {
    title: "일상 - 동물",
    template: (en) => `I saw a ${en} at the zoo.`,
    templateKo: (ko) => `동물원에서 ${ko}을(를) 봤어요.`,
    words: [
      ["dog", "개"], ["cat", "고양이"], ["bird", "새"], ["fish", "물고기"], ["rabbit", "토끼"],
      ["hamster", "햄스터"], ["horse", "말"], ["cow", "소"], ["pig", "돼지"], ["sheep", "양"],
      ["lion", "사자"], ["tiger", "호랑이"], ["elephant", "코끼리"], ["bear", "곰"], ["wolf", "늑대"],
      ["fox", "여우"], ["deer", "사슴"], ["squirrel", "다람쥐"], ["turtle", "거북이"], ["snake", "뱀"],
    ],
  },
  {
    title: "일상 - 자연/환경",
    template: (en) => `We should talk more about ${en}.`,
    templateKo: (ko) => `${ko}에 대해 더 얘기해봐야 해요.`,
    words: [
      ["the forest", "숲"], ["rivers", "강"], ["lakes", "호수"], ["the ocean", "바다"],
      ["mountains", "산"], ["valleys", "계곡"], ["deserts", "사막"], ["glaciers", "빙하"],
      ["ecosystems", "생태계"], ["pollution", "오염"], ["recycling", "재활용"],
      ["sustainability", "지속가능성"], ["climate change", "기후 변화"],
      ["renewable energy", "재생 에너지"], ["wildlife", "야생동물"], ["deforestation", "삼림 벌채"],
      ["biodiversity", "생물다양성"], ["greenhouse gases", "온실가스"], ["conservation", "보존"],
      ["carbon footprints", "탄소발자국"],
    ],
  },
  {
    title: "일상 - 도시/장소",
    template: (en) => `There's a nice ${en} near my place.`,
    templateKo: (ko) => `저희 집 근처에 괜찮은 ${ko}이(가) 있어요.`,
    words: [
      ["downtown area", "시내"], ["suburb", "교외"], ["neighborhood", "동네"], ["skyscraper", "고층빌딩"],
      ["park", "공원"], ["plaza", "광장"], ["alley", "골목"], ["intersection", "교차로"],
      ["sidewalk", "인도"], ["streetlight", "가로등"], ["apartment complex", "아파트 단지"],
      ["shopping center", "쇼핑센터"], ["city hall", "시청"], ["fire station", "소방서"],
      ["community center", "주민센터"], ["landmark building", "랜드마크 건물"],
      ["residential area", "주거지역"], ["industrial area", "산업지역"], ["historic district", "역사 지구"],
      ["waterfront", "수변 지역"],
    ],
  },
  {
    title: "일상 - 직업",
    template: (en) => `My cousin works as a ${en}.`,
    templateKo: (ko) => `제 사촌은 ${ko}(으)로 일해요.`,
    words: [
      ["doctor", "의사"], ["teacher", "교사"], ["engineer", "엔지니어"], ["lawyer", "변호사"],
      ["nurse", "간호사"], ["accountant", "회계사"], ["chef", "요리사"], ["firefighter", "소방관"],
      ["police officer", "경찰관"], ["architect", "건축가"], ["electrician", "전기 기술자"],
      ["plumber", "배관공"], ["pilot", "조종사"], ["journalist", "기자"], ["scientist", "과학자"],
      ["designer", "디자이너"], ["entrepreneur", "사업가"], ["farmer", "농부"],
      ["veterinarian", "수의사"], ["photographer", "사진작가"],
    ],
  },
  {
    title: "일상 - 시간 표현",
    template: (en) => `${en}, things have gotten busier.`,
    templateKo: (ko) => `${ko} 더 바빠졌어요.`,
    words: [
      ["Nowadays", "요즘"], ["Eventually", "결국"], ["Immediately", "즉시"], ["Occasionally", "가끔"],
      ["Frequently", "자주"], ["Rarely", "드물게"], ["Beforehand", "미리"], ["Meanwhile", "그동안"],
      ["Afterward", "그 이후"], ["Recently", "최근에"], ["In advance", "미리"],
      ["At the moment", "지금"], ["From now on", "지금부터"], ["Sooner or later", "조만간"],
      ["Ahead of schedule", "예정보다 일찍"], ["Behind schedule", "예정보다 늦게"],
      ["In the meantime", "그 사이에"], ["All of a sudden", "갑자기"], ["Little by little", "조금씩"],
      ["Right away", "바로"],
    ],
  },
  {
    title: "일상 - 자주 쓰는 표현",
    template: (en) => `${en}, I think it'll work out.`,
    templateKo: (ko) => `${ko}, 잘 될 거예요.`,
    words: [
      ["By the way", "그런데"], ["In my opinion", "제 생각에는"], ["On the other hand", "반면에"],
      ["To be honest", "솔직히"], ["For example", "예를 들어"], ["In other words", "다시 말해서"],
      ["As far as I know", "제가 아는 한"], ["It depends", "상황에 따라 다르지만"],
      ["No big deal", "별일 아니지만"], ["Take your time", "천천히 하시고"],
      ["Never mind", "신경 쓰지 마시고"], ["Sounds good", "좋아요"], ["My bad", "제 실수지만"],
      ["Good point", "좋은 지적이지만"], ["I see", "그렇군요"], ["Makes sense", "이해가 되고"],
      ["That's too bad", "안타깝지만"], ["Good for you", "잘됐고"], ["Whatever works", "편한 대로,"],
      ["Fingers crossed", "행운을 빌며,"],
    ],
  },
  {
    title: "일상 - 형용사",
    template: (en) => `This place is really ${en}.`,
    templateKo: (ko) => `여기 정말 ${ko}.`,
    words: [
      ["convenient", "편리해요"], ["exhausting", "지치게 해요"], ["reliable", "믿을 만해요"],
      ["complicated", "복잡해요"], ["straightforward", "간단해요"], ["flexible", "유연해요"],
      ["crowded", "붐벼요"], ["spacious", "넓어요"], ["cozy", "아늑해요"], ["noisy", "시끄러워요"],
      ["quiet", "조용해요"], ["affordable", "저렴해요"], ["expensive", "비싸요"],
      ["efficient", "효율적이에요"], ["outdated", "구식이에요"], ["modern", "현대적이에요"],
      ["practical", "실용적이에요"], ["fragile", "깨지기 쉬워요"], ["durable", "내구성이 있어요"],
      ["versatile", "다목적이에요"],
    ],
  },
];

function buildFlashcards() {
  const cards = [];
  FLASHCARD_CATEGORIES.forEach((cat) => {
    cat.words.forEach(([en, ko]) => {
      cards.push({
        front: en,
        back: ko,
        example: cat.template(en),
        exampleKo: cat.templateKo(ko),
        category: cat.title,
      });
    });
  });
  return cards;
}

const FLASHCARDS = buildFlashcards();
